### ISSUE TITLE
[CircularUI][IndexPage] Page changing issue

### ISSUE THREAD

**Issue by j-troc** [Samsung/Tizen.CircularUI#100]
I have created IndexPage as in the following example:

```
<w:IndexPage xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="IndexPageSample.MainView">
    
    <w:CirclePage>
        <Label Text="1" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"/>
    </w:CirclePage>
    
    <w:CirclePage>
        <Label Text="2" HorizontalTextAlignment="Center" VerticalTextAlignment="Center"/>
    </w:CirclePage>
    
</w:IndexPage>
```

The problem is that page isn't changed properly the first time.

After moving from first to the second page, second page's content is displayed however:
* CurrentPageChanged event is not raised,
* Page indicator on top doesn't change, so it is still indicating first page
* If pages use rotary event, it is still passed to the first page.

**Comment by jkpu** [comment]
I have checked this problem. Issue was reproduced always. 
I found some bug in IndexPage renderer. this issue was fixed at https://github.com/Samsung/Tizen.CircularUI/pull/106
