### ISSUE TITLE
[CircularUI][PopupEntry]  TextChanged and Completed events issue

### ISSUE THREAD

**Issue by j-troc** [Samsung/Tizen.CircularUI#101]
TextChanged and Completed events seem to be raised incorrectly in PopupEntry:

* TextChanged event is raised only after user finishes entering text instead of every time text is modified,
* Completed event is not raised when user finishes entering text

This PopupEntry behaviour is different than Entry behaviour.

**Comment by idkiller** [comment]
This issue looks resolved in PR #108
