### ISSUE TITLE
[CircularUI][TwoButtonPage] TwoButtonPage with ListView issue

### ISSUE THREAD

**Issue by t-zalewski** [Samsung/Tizen.CircularUI#102]
Hi,

I want to use a ListView with binding on my TwoButtonPage. Problem is that when I am using ListView i can't focus or tap first and last item.

![listview](https://user-images.githubusercontent.com/11194646/44709485-48a08e00-aa99-11e8-9dfa-530027ad94d1.png)

```XML
<w:TwoButtonPage.Content>
        <ListView ItemTapped="ListView_ItemTapped">
            <ListView.ItemsSource>
                <x:Array Type="{x:Type sys:String}">
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                    <x:String>Item 3</x:String>
                    <x:String>Item 4</x:String>
                    <x:String>Item 5</x:String>
                    <x:String>Item 6</x:String>
                </x:Array>
            </ListView.ItemsSource>
        </ListView>
    </w:TwoButtonPage.Content>

    <w:TwoButtonPage.FirstButton>
        <MenuItem/>
    </w:TwoButtonPage.FirstButton>

    <w:TwoButtonPage.SecondButton>
        <MenuItem/>
    </w:TwoButtonPage.SecondButton>
```

When i change ListView to CircleListView the page is not rendering properly

![circlelistview](https://user-images.githubusercontent.com/11194646/44709501-50603280-aa99-11e8-980f-692893acb29d.png)

Emulator binary version: tizen-4.0-unified_20180728.1

Nuget package version: 1.0.0-pre2-00085

**Comment by jkpu** [comment]
In Xamarin ListView, First item and last item can't be focused and tapped because of Tizen Native EFL limitation in the wearable target. In Tizen wearable device,  EFL listview item can be focused and tapped in vertical center. but the first and last item can be located in the vertical center. If user has header and footer all item can be focused and tapped.
To avoid this problem. CircularUI handles this issue internally. so user can tap first and last item.

I checked with CircleList view in TwoButtonPage. It works well. please refer to code snippet.

![dump_screen](https://user-images.githubusercontent.com/31116585/44722351-c4392400-ab07-11e8-8641-f05a1101f55b.png)


```XML
<w:TwoButtonPage
	x:Class="WearableUIGallery.TC.TCTwoButtonPage"
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:local="clr-namespace:WearableUIGallery.TC"
	xmlns:sys="clr-namespace:System;assembly=netstandard"
	xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
	Title="{Binding Title}"
	w:CircleSurfaceEffectBehavior.RotaryFocusObject="{x:Reference circleList}"
	Overlap="True">
	<w:TwoButtonPage.BindingContext>
		<local:TCTwoButtonPageViewModel />
	</w:TwoButtonPage.BindingContext>
	<w:TwoButtonPage.Behaviors>
		<w:CircleSurfaceEffectBehavior />
	</w:TwoButtonPage.Behaviors>
	<w:TwoButtonPage.Content>
		<w:CircleListView x:Name="circleList" ItemTapped="ListView_ItemTapped">
			<w:CircleListView.ItemsSource>
				<x:Array x:Key="array" Type="{x:Type sys:String}">
					<x:String>Item 1</x:String>
					<x:String>Item 2</x:String>
					<x:String>Item 3</x:String>
					<x:String>Item 4</x:String>
					<x:String>Item 5</x:String>
					<x:String>Item 6</x:String>
				</x:Array>
			</w:CircleListView.ItemsSource>
			<w:CircleListView.ItemTemplate>
				<DataTemplate>
					<TextCell Text="{Binding .}" />
				</DataTemplate>
			</w:CircleListView.ItemTemplate>
 </w:CircleListView>
```

**Comment by jkpu** [comment]
refer to upper code snippet. this is not issue.

**Comment by t-zalewski** [comment]
Hey,
I checked your snippet and adding CircleSurfaceEffectBehavior is resolving my problem. I also found out that the problem with rendering is occuring when I try to PushModal this page. When I push it normally it renders fine. Is it a bug or shouldn't I use push modal with pages like these?
