### ISSUE TITLE
[CircularUI][PopupEntry] Keyboard type issue

### ISSUE THREAD

**Issue by t-zalewski** [Samsung/Tizen.CircularUI#104]
Hi,

Changing Keyboard type property in PopupEntry is not changing anything at all. I want to use Numeric Keyboard in my PopupEntry but it doesn't work.

```XML
<w:PopupEntry Placeholder="PopupEntry"
              Keyboard="Numeric"/>
```

![popupentry](https://user-images.githubusercontent.com/11194646/44709972-8e118b00-aa9a-11e8-8dcc-8db481d5f5f2.png)

Changing this property in normal Entry gives me what I should expect.

```XML
<Entry Placeholder="Entry"
       Keyboard="Numeric"/>
```

![entry](https://user-images.githubusercontent.com/11194646/44709994-9a95e380-aa9a-11e8-8f5d-a6815d7a718b.png)

Emulator binary version: tizen-4.0-unified_20180728.1

Nuget package version: 1.0.0-pre2-00085

**Comment by idkiller** [comment]
This issue looks resolved in PR #108
