### ISSUE TITLE
[Tizen.CircularUI] [CircleListview] Strange effect at the bottom of ListView

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#115]
I am using CircleListView with DataTemplate that contains Label and Radio. I noticed some a really small list element at the bottom of the screen. It's so small that picture needs to be enlarged I marked it with red square.

![listviewflicker](https://user-images.githubusercontent.com/39958609/45091435-bf313180-b112-11e8-92cb-9eab81b137f8.png)

I tried to fix it by changing size of listview but with no effect. Still I think it should not be working like that.

See also (src included): TNEXT-16722

**Comment by jkpu** [comment]
This is not issue. CircleListview use FishEye mode. so Listview bottom and top item is too smaller than center Item. If your App List item height is not match to Windowsize. this issue is happend. so we recommand to set Height request value to 120. 3 list item will be fit window.

**Comment by jsobczuk** [comment]
Ok It's good now, thanks.

My designer set size of list item at 109. I think it was taken from Wearable UX Guide, so a change to UX Guide should be considered (or some additional information for people using CUI).

Br
jsobczuk
