### ISSUE TITLE
[CircularUI][CircleListView] Header behavior is inconsistent and causes the list to be displayed incorrectly.

### ISSUE THREAD

**Issue by mszperna** [Samsung/Tizen.CircularUI#119]
Hello!
I'm Samsung developer, I'm creating an application for the Wearable profile, I use the CircularListView control from your library. However, I have a big problem. I add a header to the list. I also set CircleListView.CancelEffect attribute to 'true'. And here appears an issue. For a list that uses grouping (IsGroupingEnabled="True") everything is displayed correctly, but if the list does not use grouping, there is an issue with elements: the header is not visible at all, and the list elements move in such a way that the first one is not available at all, and the focus by default is on the second element. The same code is used both in one version of the list and in the other, giving different effects:
List with groups (OK):
![groups_ok](https://user-images.githubusercontent.com/31132452/45355419-a2887400-b5c0-11e8-96ff-fc772ff9f7cf.png)

List without groups (Wrong):
![without_groups_wrong](https://user-images.githubusercontent.com/31132452/45355586-014ded80-b5c1-11e8-908c-f22246b34216.png)

Source code - DataTemplate which I use for both lists:

```cs
<w:CircleListView.HeaderTemplate>
	<DataTemplate>
		<Label w:CircleListView.CancelEffect="True"
			   FontSize="10"
			   HorizontalTextAlignment="Center"
			   Text="{Binding .}"
			   TextColor="#4CCDFC"
			   VerticalTextAlignment="Center" />
	</DataTemplate>
</w:CircleListView.HeaderTemplate>
```

You can clearly see that the header behavior for a list without groups is incorrect. It should look like this:
![without_groups_ok](https://user-images.githubusercontent.com/31132452/45355603-10cd3680-b5c1-11e8-853e-c590b3df6656.png)

There is a workaround by adding the HeightRequest attribute (e.g. HeightRequest="120"), but this is only a workaround, not a solution to the problem and I can't use it in my application.

Therefore, please correct this bug and tell me when to expect a new version of CircularUI library, which will be free of this issue?

Best regards

**Comment by idkiller** [comment]
According to an internal UX guideline, Header has 83px if placed before the group header or has 115px.
so I set the minimum height to CircleListView renderer.

**Comment by mszperna** [comment]
It works now, thanks :)

**Comment by Bradleyland** [comment]
@mszperna Hello, I know this is a very old post, but I have been searching forever it seems. So hopefully you can help me. 
I'm using a CirclelistView like you are in this post. I notice that you a second smaller label appear on each item as you scroll. How do you do that? How do you know when an item in the listview is in the center?
I've tried itemSelected but that only fires when the list is not scrolling the user taps again on the item. 

Any help is much appreciated. Thank you
