### ISSUE TITLE
[CircularUI] Buttons color cannot be changed.

### ISSUE THREAD

**Issue by mszperna** [Samsung/Tizen.CircularUI#120]
Hello,
I use your CircularUI library to create Tizen applications. Unfortunately I noticed that it is not possible to change the color of the button either for CircularPage or for Popup. This option is necessary for the design and development of applications, also available guides use this feature (see: outgoing calls or ending a call, where buttons are red and green).
Are there plans to implement this feature in the near future? This is very important.

Regards

**Comment by jkpu** [comment]
I added Color property for your request
https://github.com/Samsung/Tizen.CircularUI/pull/132
Please check with latest nuget package. you can refer to WearableUIGallery TC for how to use this property.
