### ISSUE TITLE
[CircularUI][CircleScrollView] Resizing issue

### ISSUE THREAD

**Issue by j-troc** [Samsung/Tizen.CircularUI#124]
I have been changing visibility of elements within CircleScrollView. After doing that they are displayed incorrectly, they are offset and it's not possible to scroll down to the bottom ones.

I have created following example page:

.xaml
```
<?xml version="1.0" encoding="utf-8" ?>
<w:CirclePage xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms" 
              xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TizenWearableApp3.Page1"
             RotaryFocusObject="{x:Reference myscroller}">

    <w:CircleScrollView  x:Name="myscroller">
        <StackLayout  
            Orientation="Vertical"
            VerticalOptions="FillAndExpand">

            <Label BackgroundColor="DarkOliveGreen" HeightRequest="250"/>
           
            <Label x:Name="hideable" BackgroundColor="red" HeightRequest="300"/>

            <Button x:Name="button" Text="Press me"/>
        </StackLayout>
    </w:CircleScrollView>
</w:CirclePage>
```
.xaml.xs 
```
    public partial class Page1 : CirclePage
    {
        public Page1()
        {
            InitializeComponent();
            button.Clicked += (s, e) => hideable.IsVisible = !hideable.IsVisible;
        }
    }
```

In this example there are two labels and a button. Pressing button hides red label.

![before](https://user-images.githubusercontent.com/41898222/45824985-7cb24c00-bcf1-11e8-97d7-cd6659b8d49a.png)

Hiding red label causes layout to be displayed invalidly:

![after](https://user-images.githubusercontent.com/41898222/45824988-7f14a600-bcf1-11e8-975a-3397fb50fb0f.png)

**Comment by jkpu** [comment]
I fixed this issue at #125 
You can check TC of wearableUIGallery TC  ( launch WearableUIGallery > ScrollView > remove/add tc   ) or please check with latest nuget package.
