### ISSUE TITLE
[Tizen.CircularUI] [Changing colors] Enhancement request

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#129]
Hi

Our designers sometimes want to create applications that are diffrent from default 'black and blue' design that is provided by CircularUI controls. For example our designer wanted to change ActionButton color so we went to discussion if we should use CircularUI ActionButton or one that is available from Xamarin.Forms (it was added recently and it can change it's color). At this moment we cannot create applications using CircularUI that are compatible with designers' guides.

Please consider changing color option for these controls :

    1. Changing color of Scroll Bar.
    2. Changing color of Progress Indicator and Activity Indicators.
    3. Two colors for EntryPopup : BackGroundColor and KeyboardScreenBackgroundColor (so we can set other color while on screen with Keyboard popup).
    4. Changing color of ActionButton (already requested by m.szperna) , LeftButton (FirstButton) and RightButton (SecondButton).
    5. Changing color of select mode in ActionButton , LeftButton(FirstButton) and RightButton(SecondButton).
    6. Changing color of Radio.
    7. Changing color of Check.
    8. Changing focus image in CircleListView.

Such enhancement would make CircularUI flexible in term of design needs.

Best regards
j.sobczuk

**Comment by mszperna** [comment]
I can confirm that adding the above-mentioned features is extremely important and very useful. It will allow to develop a variety of custom applications.

**Comment by jkpu** [comment]
I added Color property for your request 
https://github.com/Samsung/Tizen.CircularUI/pull/132
Please check with latest nuget package. you can refer to WearableUIGallery TC for how to use this property.

**Comment by jsobczuk** [comment]
Is it accessible via MyGet?

**Comment by jkpu** [comment]
Yes, You can access latest pre-release nuget package via Myget.

1.0.0-pre2-00112 (modifications were applied this version )
Friday, October 26, 2018 (10/26/2018)
