### ISSUE TITLE
[CircularUI][PopupEntry] OnTextEntered issue

### ISSUE THREAD

**Issue by j-troc** [Samsung/Tizen.CircularUI#131]
I'm trying to modify Popupentry's text in OnTextEntered event however modifying it does not change displayed text and when next character is entered whole text is set again.

```
private void OnTextChanged(object sender, TextChangedEventArgs e)
{
   var entry = (PopupEntry)sender;
   Log.Debug("Test", $"{e.NewTextValue}, {e.OldTextValue}");
   entry.Text = "";
}
```

Text should be cleared every time OnTextChanged is executed however next time e.NewTextValue contains all characters entered not only newest one.

```
D/Test    ( 3147): Test.cs: OnTextChanged(135) > m,
D/Test    ( 3147): Test.cs: OnTextChanged(135) > , m
D/Test    ( 3147): Test.cs: OnTextChanged(135) > mn,
D/Test    ( 3147): Test.cs: OnTextChanged(135) > , mn
D/Test    ( 3147): Test.cs: OnTextChanged(135) > mnd,
D/Test    ( 3147): Test.cs: OnTextChanged(135) > , mnd
```

**Comment by jkpu** [comment]
This issue was fixed at PR(https://github.com/Samsung/Tizen.CircularUI/pull/133)
