### ISSUE TITLE
[Tizen.CircularUI][CircleScrollView] Cannot use CircleScrollView on TwoButtonPage

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#137]
Hi

Problem occurs when I'm trying to add CircleScrollView to TwoButtonPage content. Adding CircleScrollView causes application crash. I know that there is an InformationPopup control available but I need custom icons for FirstButton and SecondButton , and other custom elements on the screen.

```cs
<cui:TwoButtonPage.Content>
        <AbsoluteLayout>
            <cui:CircleScrollView AbsoluteLayout.LayoutBounds="76, 63, 208, 222"
                        VerticalScrollBarVisibility="Never">
                <Label Text="{Binding ResultText}"
                       TextColor="#FFFFFF"
                       FontFamily="SamsungOne"
                       FontSize="9.75" />
            </cui:CircleScrollView>
        </AbsoluteLayout>
</cui:TwoButtonPage.Content>
```

Problem does not occur when using CirclePage.

I will upload sample application showing the problem if needed.

Best regards
j.sobczuk

**Comment by jkpu** [comment]
TwoButtonPage doesn't support CricleScrollView.
please refer to guide.  https://samsung.github.io/Tizen.CircularUI/guide/CircleScrollView.html

> WARNING: CircleListView, CircleDateTimeSelector, CircleScrollView, CircleStepper must be confined in the CirclePage container or Page with CircleSurfaceEffectBehavior. If you add these controls in any other way, it may cause an exception or cannot display the controls. 
> 

This is normal operation  not issue.

**Comment by axa88** [comment]
> with CircleSurfaceEffectBehavior. If you add these controls in any other way, it may cause an exception or can

Yet Samsung official samples recommend using CircleScrollView in TwoButtonPage:

[TCTwoButtonPage.xaml](https://github.com/Samsung/Tizen.CircularUI/blob/master/test/WearableUIGallery/WearableUIGallery/TC/TCTwoButtonPage.xaml)

**Comment by jkpu** [comment]
[TCTwoButtonPage.xaml](https://github.com/Samsung/Tizen.CircularUI/blob/master/test/WearableUIGallery/WearableUIGallery/TC/TCTwoButtonPage.xaml) also use `CircleSurfaceEffectBehavior` in TwoButtonPage.
Please see below codes. this code set Behavior of TwoButtonPage

```xml
    <w:TwoButtonPage.Behaviors>
        <w:CircleSurfaceEffectBehavior />
    </w:TwoButtonPage.Behaviors>
```

```xml
<w:TwoButtonPage
	x:Class="WearableUIGallery.TC.TCTwoButtonPage"
	xmlns="http://xamarin.com/schemas/2014/forms"
	xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	xmlns:local="clr-namespace:WearableUIGallery.TC"
	xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
    w:CircleSurfaceEffectBehavior.RotaryFocusObject="{x:Reference myscroller}"
	Title="{Binding Title}}">
    <w:TwoButtonPage.Behaviors>
        <w:CircleSurfaceEffectBehavior />
    </w:TwoButtonPage.Behaviors>
```
