### ISSUE TITLE
Custom fonts not working in Tizen .NET

### ISSUE THREAD

**Issue by Digifais** [Samsung/Tizen.CircularUI#139]
Custom fonts are not working in Tizen .NET as described by the following guide: [https://samsung.github.io/Tizen.CircularUI/guide/HowToSetTheCustomFont.html](https://samsung.github.io/Tizen.CircularUI/guide/HowToSetTheCustomFont.html)

```
    class Program : Xamarin.Forms.Platform.Tizen.FormsApplication
    {
        protected override void OnCreate()
        {
            base.OnCreate();

            Utility.AppendGlobalFontPath(Current.DirectoryInfo.Resource);

            LoadApplication(new App(new AppSetup()));
        }

        static void Main(string[] args)
        {
            var app = new Program();
            Xamarin.Forms.Platform.Tizen.Forms.Init(app);
            global::Tizen.Wearable.CircularUI.Forms.Renderer.FormsCircularUI.Init();
            app.Run(args);
        }
    }
```

I add the resources path as a global font path as described in the guide and then try to set the FontFamily of a Label control in XAML to the PostScript name of the font as described in the guide, but it doesn't do anything.

You can find the fonts in this ZIP file attached here: 
[Lato Fonts.zip](https://github.com/Samsung/Tizen.CircularUI/files/2698345/Lato.Fonts.zip)

**Comment by jkpu** [comment]
Could you write your code of label that used the custom font(Lato font).
Above code snippet has only including font resource using "Utility.AppendGlobalFontPath".
In the guide, custom font postscriptname (e.g YiSunShinBold) should be inserted at Label code. 
please refer to below code.


 new Label {
       HorizontalTextAlignment = TextAlignment.Center,
       FontFamily = "YiSunShinBold",
       Text = "Welcome to Xamarin Forms!"
  }


**$fc-query ./Lato-Bold.ttf** 

```
Pattern has 22 elts (size 32)
	family: "Lato"(s)
	familylang: "en"(s)
	style: "Bold"(s)
	stylelang: "en"(s)
	fullname: "Lato Bold"(s)
	
.............................


	decorative: False(s)
	hash: "sha256:14f7de6b616950395062902eb8f70f01c0a901223db5d40f2a05728ac4a830f6"(s)
	postscriptname: "Lato-Bold"(s)
```



You should insert FontFamily value with "Lato-Bold".

                    new Label {
                            HorizontalTextAlignment = TextAlignment.Center,
                            FontFamily = "Lato-Bold",
                            Text = "Welcome to Xamarin Forms!"
                        }

**Comment by jkpu** [comment]
When I have tested with following to the guide. Custom font is working properly 
But only attached your custom font(Lato-Bold) was not applied.

 <Device default font>
![device_default_font](https://user-images.githubusercontent.com/31116585/50391010-c17ed080-0781-11e9-9dc0-0fba6b0d0182.png)



<Yisunshin font at the guide>
![yisunsin_font](https://user-images.githubusercontent.com/31116585/50391012-c774b180-0781-11e9-8731-94da1a894a30.png)


<Bloomsburg font that I downloaded internet>
![bloomsburg_font](https://user-images.githubusercontent.com/31116585/50391020-dd827200-0781-11e9-9520-26258dcaabd9.png)



As you can see, only Lato-Bold is not working. Maybe your custom font has a problem. 
Please check with other font file. 
I'm attaching my test app code. please refer to the following code. 


[TizenWearableXamlApp2.zip](https://github.com/Samsung/Tizen.CircularUI/files/2706625/TizenWearableXamlApp2.zip)

**Comment by jkpu** [comment]
When I have tested more font file with downloading from the internet. Some font file was not applied as
_"postscriptname"_.
I found the way fixing this problem. Setting FontFamily property with real _family name_ will work properly. and style can be set with FontAttribute property. 
Please refer to following code and attached test app code. 
You can find the way appliying your custom font.

```
  <Label Text="Lato Regular"
       FontFamily="Lato" />

  <Label Text="Lato Bold"
       FontFamily="Lato"
       FontAttributes="Bold" />

  <Label Text="Lato BoldItalic"
       FontFamily="Lato"
       FontAttributes="Bold, Italic" />
````

![dump_screen](https://user-images.githubusercontent.com/31116585/50466924-85e34100-09e3-11e9-8be9-f53e10d3d5f1.png)

[TizenWearableXamlApp2.zip](https://github.com/Samsung/Tizen.CircularUI/files/2711526/TizenWearableXamlApp2.zip)

**Comment by Digifais** [comment]
Thanks for the amazing support jkpu, I can confirm this does work!
