### ISSUE TITLE
[CircularUI][IndexPage] Adding pages with single start page doesn't work as expected

### ISSUE THREAD

**Issue by msioen** [Samsung/Tizen.CircularUI#147]
Issue setup:
- IndexPage with a single contentpage as child
- Add a new child dynamically

Expected:
- Indexdots on top show 2 pages
- Swipe is possible to the new page

Actual:
- Index dots do update (child is correctly added)
- Swipe is NOT possible

If the initial contentpage has more than one child this issue doesn't occur.

I've added an example page to the test project in my fork demonstrating this issue with a possible fix. https://github.com/msioen/Tizen.CircularUI/tree/indexpage-issues
The repro and the possible fix are in separate commits for clarity.

I'll make a pr with my changes but I'm not sure if my workaround is the ideal solution here (It is functional though). The problem seems to be that _innerContainer.Geometry.Size doesn't reflect the correct size but I'm not sure why. If the flow could be changed to fix that the extra child count check might not be necessary

**Comment by jkpu** [comment]
Thank you for your contribution of fixing IndexPage issue.
I found some behavior change in native UI framework of the Tizen.  _innerContainer.Geometry.Size doesn't reflect the correct size when  _innerContainer Box is packing. 
 I don't know why this behavior has been changed. but your code is good to resolve this problem  and has no side effect.
