### ISSUE TITLE
Bug using ActionButtonItem

### ISSUE THREAD

**Issue by kellison3205** [Samsung/Tizen.CircularUI#162]
[TizenWearableXamlApp1.zip](https://github.com/Samsung/Tizen.CircularUI/files/2877242/TizenWearableXamlApp1.zip)

I get an exception when clicking on ActionButtonItem.  I tried using a Command and Clicked. I got an the error both times. I'm attaching a simple test case.

I am using Xamarin Version 3.5.0.129452
Tizen.NET 4.0.0
Tizen.Net.Sdk 1.0.1
Tizen.Wearable.CircularUI 1.0.0

from log filtered for DOTNET_LAUNCHER:

02-17 09:58:16.450	Info	3981	3988	DOTNET_LAUNCHER	Unhandled Exception: 
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	System.MissingMethodException: Method not found: 'Void Xamarin.Forms.MenuItem.Activate()'.
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at Tizen.Wearable.CircularUI.Forms.Renderer.CirclePageRenderer.OnActionButtonClicked(Object sender, EventArgs e)
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at ElmSharp.Button.<.ctor>b__4_0(Object sender, EventArgs e)
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at ElmSharp.SmartEvent.SendEvent(Object sender, EventArgs e)
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at ElmSharp.SmartEvent`1.<>c__DisplayClass12_0.<add_On>b__0(IntPtr d, IntPtr o, IntPtr e)
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at Tizen.Applications.CoreApplication.Run(String[] args)
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at Tizen.Applications.CoreUIApplication.Run(String[] args)
02-17 09:58:16.580	Info	3981	3988	DOTNET_LAUNCHER	   at TizenWearableXamlApp1.Program.Main(String[] args) in C:\Users\kelli\source\repos\TizenWearableXamlApp1\TizenWearableXamlApp1\TizenWearableXamlApp1.cs:line 20

**Comment by jkpu** [comment]
Thank you for your issue reporting.

This Exception due to some interface has been chagned in Xamarin.Forms Version 3.5.0.129452.
Tizen.Wearable.CircularUI V1.1.0-pre1-00013 is supporting Xamarin.Forms Version 3.5.0.129452.
you can fix this exception with CircularUI version updating.
