### ISSUE TITLE
Calling Focus on PopupEntry does nothing

### ISSUE THREAD

**Issue by MaxGsomGsom** [Samsung/Tizen.CircularUI#165]
I suppose this code should show keyboard on page appearing, but it does not:
```
public class SendMessagePage : CirclePage
    {
        private readonly PopupEntry popupEntryView = new PopupEntry();

        public SendMessagePage()
        {
            Content = popupEntryView;
        }

        protected override void OnAppearing()
        {
            popupEntryView.Focus();
            base.OnAppearing();
        }
    }
```
Emulator: W4.0-circle-x86-preview-26101
Tizen.Wearable.CircularUI 1.1.0-pre1-00013

**Comment by yourina** [comment]
Hello, @MaxGsomGsom 
It is difficult to check whether SendMessagePage method is called or not with the above example code. 
Could you share more information? 
Thank you for reporting.

**Comment by MaxGsomGsom** [comment]
OnAppearing method is called every time when page is shown on screen. You can test it by creating simplest app:
```
public class App : Application
    {
        protected override void OnStart()
        {
            MainPage = new SendMessagePage();
        }
    }
```

**Comment by yourina** [comment]
Hello, @MaxGsomGsom 
Thank you for providing more information. 
Unfortunately, basic operation of 'Focus() ' is to change focus status of 'PopupEntry', not to show Keyboard on Popup. 
But, we agree the necessity of your requirement. So, we  decided to provide new method as 'ShowPopup'. The basic operation of 'ShowPopup' is to create Popup and to show keyboard with entry.
We are waiting for your opinion.. 
Thank you.

**Comment by MaxGsomGsom** [comment]
I have read some more info and found that I need to implement my own view renderer to use this feature
