### ISSUE TITLE
CircleListView with Radio control bug

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#173]
**Describe the bug**
I have a CircleListView and inside every element I have a cui:Radio control, which InputTransparent property is set to "True". I want Radio control to be transparent for clicks. Problem is that this solution was working at 4.0 Wearable Emulator, but it's not working in 5.0 Wearable emulator.

**To Reproduce**
Page that produces bug:
[SilenceDetectionPage.xaml.zip](https://github.com/Samsung/Tizen.CircularUI/files/2977569/SilenceDetectionPage.xaml.zip)

My emulator versions:
- wearable emulator 4.0 version -> 20181115.1
- wearable emulator 5.0 version -> 20190315.2

1.Problem occurs when clicking Radio controls that are not SelectedItem. They all should change state only on SelectedItem setter because InputTransparent="True". To test it, just click on radio that is one element below the selected one.
2. Test this solution on wearable emulator 4.0. (Works)
3. Test this solution on wearable emulator 5.0. (Fails)

**Screenshots**
5.0 Emulator (Fails) ->
![circleBug1](https://user-images.githubusercontent.com/39958609/54524976-81d81700-4973-11e9-998a-c4fabc713022.PNG)
4.0 Emulator (Works) ->
![circleBug2](https://user-images.githubusercontent.com/39958609/54525031-95837d80-4973-11e9-9598-2b7ed476d086.PNG)

**Environment**
 - Tizen.NET - 5.0.0.14562
 - Tizen.CircularUI - 1.1.0-pre1-00021

**Comment by jkpu** [comment]
Thanks you for your issue reporting.
Tizen 5.0 wearable is not stable as you can see above screen shot (list view is cropped), and has manay Native EFL issue. I can't fix this issue because I'm not charge of Native EFL.
There is no Tizen 5.0 wearable Target except tizen 5.0 emulator. 
Tizen CircularUI nuget 1.0.0 ~ 1.1.0 supports Tizen 4.0 devices and emulator and Tizen.NET - 4.0.0 in now. So I recommand you use tizen 4.0 emulator and Tizen.NET - 4.0.0 .

**Comment by jsobczuk** [comment]
Thanks for replying.
We had a decision made in our team that we will be developing for 5.0 only. I showed your post to my supervisor and we are back to 4.0 now, so your post was very helpful in this situation :)

Could you tell me if anyone is working on this issues and when we can expect some changes related to this?

Thanks
j.sobczuk
