### ISSUE TITLE
ActionButton only displaying on the first page of an IndexPage

### ISSUE THREAD

**Issue by Jamiek94** [Samsung/Tizen.CircularUI#185]
**Describe the bug**
Only a single action button is displayed on the first page of an index page. It should display an action button on all the pages within the index page.

**To Reproduce**
```
<?xml version="1.0" encoding="utf-8" ?>
<w:IndexPage xmlns="http://xamarin.com/schemas/2014/forms"
              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
              xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
             x:Class="Domoticz.MainPage">

    <w:CirclePage>
        <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
            <Label Text="IP" />
            <Entry />
        </StackLayout>
        <w:CirclePage.ActionButton>
            <w:ActionButtonItem
                x:Name="IpButton"
                Text="Next"/>
        </w:CirclePage.ActionButton>
    </w:CirclePage>

    <w:CirclePage>
        <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
            <Label Text="Username" />
            <Entry />
        </StackLayout>

        <w:CirclePage.ActionButton>
            <w:ActionButtonItem
                Text="Next"/>
        </w:CirclePage.ActionButton>
    </w:CirclePage>

    <w:CirclePage>
        <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
            <Label Text="Password" />
            <Entry />
        </StackLayout>
        <w:CirclePage.ActionButton>
            <w:ActionButtonItem
                Text="Login"/>
        </w:CirclePage.ActionButton>
    </w:CirclePage>

</w:IndexPage>
```

**Expected behavior**
An actionbutton on each circle page.

**Screenshots**
![first-page](https://user-images.githubusercontent.com/4362445/56474455-6bddda80-647a-11e9-8eed-de9c9fbfcf9e.png)
![second-page](https://user-images.githubusercontent.com/4362445/56474456-6bddda80-647a-11e9-9c3b-b5637b0a73fb.png)

**Environment (please complete the following information):**
 - Gear S3
 - Tizen 4.0
 - Tizen.CircularUI Version1.0

**Comment by jkpu** [comment]
Thanks you for issue reporting.
I have verified this issue is always reproducible on emulator and Watch device.
I fixed this issue at (https://github.com/Samsung/Tizen.CircularUI/pull/187) and it will included  in Tizen.CircularUI nuget v1.2.0 release version.

And, I recommend you to use PopupEntry instead of Entry in above code. 
If you use Entry with an ActionButton, the following display issue occurs.

```
        <StackLayout HorizontalOptions="Center" VerticalOptions="Center">
            <Label Text="IP" />
            <w:PopupEntry />
        </StackLayout>
```

![entry](https://user-images.githubusercontent.com/31116585/56489341-65a03a80-651c-11e9-8ef3-798969e52cc3.png)
