### ISSUE TITLE
Bezel not working for watches updated to 4.0.0.4

### ISSUE THREAD

**Issue by DamianMehers** [Samsung/Tizen.CircularUI#192]
**Describe the bug**
An existing released app that uses CircularUI to support the bezel no longer works with the Bezel once the watch is upgraded to Tizen 4.0.0.4

**To Reproduce**
Build an app using CircularUI and run it on a watch that has a bezel.

**Expected behavior**
The bezel works on a watch that does has a bezel (S3, Galaxy Watch, etc.) for apps using CircularUI

**Environment (please complete the following information):**
Tizen 4.0.0.4, latest released Tizen.CircularUI

**Additional context**
My customers are complaining to me that the Bezel no longer works....

**Comment by rookiejava** [comment]
@DamianMehers  Which control did you use or test?

**Comment by jkpu** [comment]
We need more information about issue. 

1. Which control(widget) of CircularUI is not working ?
Some control (circledatetime, circlestepper) UI have been changed and removed bezel interaction, User can control using gestrue instead of using bezel.

2. Can you attach the snapshot image of the issue ?

**Comment by jkpu** [comment]
Following figures are sample UI image  before and after of 4.0.0.4 in CircleStepper and CircleDateTimeSelector.

1.CircleStepper 

|          Before                      |              After                           | 
|:---------------------------:|:-------------------------------:|
|  ![image2019-1-7_11-25-59](https://user-images.githubusercontent.com/31116585/58145017-a27e5f00-7c8b-11e9-9eec-e56242ac1378.png)   |  ![image2019-1-7_11-26-41](https://user-images.githubusercontent.com/31116585/58145034-a9a56d00-7c8b-11e9-9581-4b79baf767bf.png) | 



2. CicleDateTimeSelector

|          Before                      |              After                           | 
|:---------------------------:|:-------------------------------:|
|  ![image2019-1-7_11-26-55](https://user-images.githubusercontent.com/31116585/58145075-ce014980-7c8b-11e9-9caa-565ddeca0a17.png)  |  ![image2019-1-7_11-27-3](https://user-images.githubusercontent.com/31116585/58145168-1c164d00-7c8c-11e9-9a2f-83d1569a9d5c.png)  |

**Comment by DamianMehers** [comment]
For me it is a very simple `CircleScrollView` that is not scrolling using the Bezel in 4.0.0.4 ... I'll try to put together a demo.  This is an app in the app store (Voice in a Can).

**Comment by DamianMehers** [comment]
I can't explain what I am seeing .. the version under beta-test which I released on Sunday, does not scroll properly (`CircularScrollView` and `CirclePage.ToolbarItems`) using the the bezel for watches that were updated to 1.0.0.4 since then ... however if I build and run the same software it does scroll.  I'll try re-submitting a beta to the store.

**Comment by rookiejava** [comment]
@DamianMehers Ok. Then, I'm going to close this ticket. Please reopen this if you found bug again. Thanks.

**Comment by DamianMehers** [comment]
> @DamianMehers Ok. Then, I'm going to close this ticket. Please reopen this if you found bug again. Thanks.

Sounds good.  I've created a new bug with a repro and a demo ... sorry for the poor quality of this initial bug report.
