### ISSUE TITLE
CirclePage.ToolbarItems do not update using Bezel on Tizen 4.0.0.4

### ISSUE THREAD

**Issue by DamianMehers** [Samsung/Tizen.CircularUI#193]
**Describe the bug**
The bezel does not change  the selected item using Tizen 4.0.0.4 Demo: https://youtu.be/HL4q7aoliQk

**To Reproduce**
1. Create a new Tizen Wearable Project and update the main page to this:
``` xaml
<?xml version="1.0" encoding="utf-8"?>

<circularui:CirclePage xmlns="http://xamarin.com/schemas/2014/forms"
              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
              xmlns:circularui="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
              RotaryFocusObject="{x:Reference TheScrollView}"
              x:Class="CircularScrollViewDemo.MainPage">
    <circularui:CirclePage.Content>
        <circularui:CircleScrollView x:Name="TheScrollView">
            <StackLayout>
                <Label Text="Welcome to Xamarin.Forms!"
                       VerticalOptions="CenterAndExpand"
                       HorizontalOptions="CenterAndExpand" />
            </StackLayout>
        </circularui:CircleScrollView>
    </circularui:CirclePage.Content>
    <circularui:CirclePage.ToolbarItems>
        <circularui:CircleToolbarItem  Text="One" IconImageSource="feedback.png"/>
        <circularui:CircleToolbarItem Text="Two"  IconImageSource="feedback.png" />
        <circularui:CircleToolbarItem Text="Three"  IconImageSource="feedback.png" />
        <circularui:CircleToolbarItem Text="Four"  IconImageSource="feedback.png" />
    </circularui:CirclePage.ToolbarItems>
</circularui:CirclePage>
```

2. Build and run on a Tizen 4.0.04 device, go to the toolbar items and use the bezel

**Expected behavior**
The selected item should change.  It does not.

**Screenshots**
Demo: https://youtu.be/HL4q7aoliQk

**Environment (please complete the following information):**
 - Target Product: S3 running Tizen 4.0.0.2 and Galaxy Watch running Tizen 4.0.0.4
 - Tizen.CircularUI Version 1.0.2

**Additional context**
Example project attached
[ToolbarBezelDemo.zip](https://github.com/Samsung/Tizen.CircularUI/files/3206070/ToolbarBezelDemo.zip)

**Comment by rookiejava** [comment]
Thank you for sharing details with us. We will take a look into it.

**Comment by jkpu** [comment]
This issue is due to changing behavior of Native UIFW in GalaxyWatch 4.0.0.4 update binary.
We can't fix this issue in CircularUI renderer. So I had reported this issue to GalaxyWatch UIFW team.
They have check this issue and they will fix this issue and apply to next update binary.

**Comment by DamianMehers** [comment]
I'm not seeing this issue any more, even with the software Bezel, so I'm going to close it unless anyone objects?
