### ISSUE TITLE
One UI update

### ISSUE THREAD

**Issue by Csaba8472** [Samsung/Tizen.CircularUI#194]
Hello

It's great to have the CircularUI it makes development much easier! Yesterday I've updated my watch to tizen 4.0.0.4 and I've noticed that my xamarin app has a pre - One UI skin. Do you have plans to implement the One UI skin in CircularUI?

Thank you!
Csaba

**Comment by tomh4** [comment]
This would be very nice :)

**Comment by rookiejava** [comment]
We are basically dependent on the platform UI. So, if you upgraded the platform to a version applying One UI (4.0.0.4), then CircularUI will render to One UI without any efforts.

**Comment by tomh4** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Does the App need to be upgraded or the device ?                                                                                                                                                                           Von: notifications@github.comGesendet: 30. Mai 2019 06:27An: Tizen.CircularUI@noreply.github.comAntworten: reply@reply.github.comCc: tomhetto@gmail.com; comment@noreply.github.comBetreff: Re: [Samsung/Tizen.CircularUI] One UI update (#194)  We are basically dependent on the platform UI. So, if you upgraded the platform to a version applying One UI (4.0.0.4), then CircularUI will render to One UI without any efforts.

**Comment by Csaba8472** [comment]
@rookiejava thank you, so new NuGet package will be released?

**Comment by rookiejava** [comment]
@Csaba8472 I hope so. We will share the specific plan again after looking at more of what we can do.

**Comment by rookiejava** [comment]
Apologies for slow progress. :pray:

We are now waiting for the internal review results.  Because this is a design-related issue, we must get prior permission from the relevant department. At the moment, I don't know when the result come out and whether it will be allowed or not.

Anyway I'm promise I will update it as soon as the results are available.

**Comment by cristian-samsung** [comment]
@rookiejava 

Hi Kangho, any updates on this?

**Comment by Csaba8472** [comment]
@rookiejava do you have any update?

**Comment by rookiejava** [comment]
@cristian-samsung @Csaba8472 
Sorry for late reply. We have worked on a variety of ways to address this issue, from [adding CircularUI's API that use OneUI](https://github.com/rookiejava/Tizen.CircularUI/tree/oneui-beta) to  to internalizing the platform itself.

We are very sorry to know that it took a very long time for the non-technical reasons I mentioned before. But what I can tell you right now is that we are still working on this issue. We hope to give you an answer as soon as possible.

**Comment by EmilAlipiev** [comment]
I am eagerly looking for this also. i hope that we can get it soon.

**Comment by rookiejava** [comment]
We are working on the goal of supporting One UI by default in upcoming Tizen platform release. Sorry again it took so loooooong. We'll appreciate your patience on this matter.

**Comment by Csaba8472** [comment]
You mean Tizen 5.0 or 5.5? Can you give us a rough estimate?

**Comment by rookiejava** [comment]
I expect it to be 5.5 or 6.0 or higher, but nothing has been set yet. And since there is still uncertainty, I am sorry that I cannot share schedule for now.

**Comment by rookiejava** [comment]
You've been waiting for a very looooooooooooong time. 🙏 

With the [official release of Tizen 5.5 M3](https://developer.tizen.org/ko/tizen/release-notes/tizen-5.5-public-m3?langredirect=1) last month, today I am pleased to inform you that the native UI framework support the OneUI by default from this version. (In other words, no additional coding is required to apply OneUI with CircularUI in your app. :-) )

The official emulator binary has not yet been updated through the Tizen SDK, but you can alternatively use the latest 5.5 M3 wearable emulator binary as shown below.

1. Download the latest emulator binary [here](http://download.tizen.org/releases/milestone/tizen/5.5-unified/tizen-5.5-unified_20200812.1/images/emulator/wearable-emulator-circle/tizen-5.5-unified_20200812.1_wearable-emulator-circle.tar.gz).
2. Extract the file (`tizen-5.5-unified_20200812.1_wearable-emulator-circle.tar.gz`).
3. Run the `Emulator Manager`.
4. Click the '+ Create' button to create a new emulator image.
5. Choose the wearable-5-5-circle-x86(basic) and Click `Next`
![image](https://user-images.githubusercontent.com/1029134/91524050-2d431480-e939-11ea-8b90-7d641c33cfcb.png)
6. Select the Image format as "raw" and enter the directory path where you extracted the compressed file in step 2.
![image](https://user-images.githubusercontent.com/1029134/91524223-a0e52180-e939-11ea-947e-184cb53c853c.png)
![image](https://user-images.githubusercontent.com/1029134/91524118-65e2ee00-e939-11ea-8ab5-6bf004c7d4c3.png)
7. Click `Next`.
![image](https://user-images.githubusercontent.com/1029134/91524242-aa6e8980-e939-11ea-9f4e-d9180c369b1c.png)
7. Click `Next`.
![image](https://user-images.githubusercontent.com/1029134/91524252-ae021080-e939-11ea-830b-146db9c07b3a.png)
7. Click `Complete`.
![image](https://user-images.githubusercontent.com/1029134/91524261-b22e2e00-e939-11ea-8f69-f4df8bc7e718.png)

Again, thank you for your patience in waiting for update.
Enjoy it!

**Comment by cristian-samsung** [comment]
This is great news, thanks Kangho!

**Comment by EmilAlipiev** [comment]
Quick and stupid question. If we develop for 5.5 version, can we run it on 5 and 4 versions as well? Is it only target version or minimum version?
