### ISSUE TITLE
PopupEntry "ReturnType" Value

### ISSUE THREAD

**Issue by cristian-samsung** [Samsung/Tizen.CircularUI#207]
**Describe the bug**
Setting the "ReturnType" value of a PopupEntry seems to have no effect.  

**To Reproduce**
Declaring a XamarinEntry like this will adjust the return value from "Done" to a search magnifying glass: 

`<Entry x:Name="XamarinEntry" Placeholder="XamarinEntry" VerticalOptions="Start" ReturnType="Search"/>`

Doing a similar method when declaring a PopupEntry seems to have no effect: 

`<forms:PopupEntry x:Name="PopupEntry" Placeholder="PopupEntry" VerticalOptions="Start" ReturnType="Search" />`

This follows across any of the [accepted values](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.entry.returntype?view=xamarin-forms#Xamarin_Forms_Entry_ReturnType) for "ReturnType".  

**Expected behavior**
Use the "ReturnType" property to set what the return value on the keyboard to something besides "Done".  

**Screenshots**
Expected Value: 
![image](https://user-images.githubusercontent.com/49006983/64822989-1f02b980-d56b-11e9-9e6b-d1ab635a2465.png)

Actual Result:
![image](https://user-images.githubusercontent.com/49006983/64822932-02668180-d56b-11e9-93f0-a47e9043b313.png)

**Environment (please complete the following information):**
 - Confirmed on Galaxy Watch & Tizen Emulator
 - Tizen Platform Version 4.0.4
 - Tizen.CircularUI Version 1.3.2

**Comment by jkpu** [comment]
Thank you for your issue reporting.
This issue was fixed PR (https://github.com/Samsung/Tizen.CircularUI/pull/208 )
This fetch will be include in next nuget release

**Comment by cristian-samsung** [comment]
Great, thanks!
