### ISSUE TITLE
PopupEntry Focused/UnFocused doesnt work

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#212]
PopupEntry inherits xamarin.forms entry but i dont get why those 2 actions arent called on my galaxy watch. Is it a bug?

**Comment by jkpu** [comment]
@EmilAlipiev Thank you for your issue reporting.
 please describe more detail problem or can you add your code snippet?  
`Action` means only focusing(visual effect) or means showing entry popup? 
PopupEntry is for specific behavior and designated widget for tizen wearable app. so some property and method of Xamarin.Forms can't be supported. so please describe what is problem and what is expected behavior.

**Comment by myroot** [comment]
Why do you want to handle Focused/Unfocused event? 
You can watch `IsPopupOpened` property changing when PopupEntry was opened
Is it working for you?

**Comment by EmilAlipiev** [comment]
I have a custom entry having a property called suffix and text is displayed with suffix. So entry text is displayed 90 kg but actually keyboard on entry is numeric. When user focuses, suffix is removed and user has 90 as numeric on focus. Visa versa when user unfocuses, in the event, i replace the text as 90 kg. I dont know how can IsPopupOpened can be used for this purpose? it has to be an event i believe.

**Comment by myroot** [comment]
It is workaround code for you
``` C#
            var entry = new PopupEntry()
            {
                Keyboard = Keyboard.Numeric
            };
            entry.PropertyChanged += (s, e) =>
            {
                if (e.PropertyName == "IsPopupOpened")
                {
                    if (e.PropertyName == "IsPopupOpened")
                    {
                        if (entry.IsPopupOpened)
                        {
                            if (entry.Text.EndsWith("kg"))
                            {
                                entry.Text = entry.Text.Substring(0, entry.Text.Length - "kg".Length);
                            }
                        }
                        else
                        {
                            if (entry.Text.Length > 0)
                                entry.Text = entry.Text + "kg";
                        }
                    }
                }
                else if (e.PropertyName == "Text")
                {
                    if (entry.IsPopupOpened)
                    {
                        if (entry.Text.EndsWith("kg"))
                        {
                            entry.Text = entry.Text.Substring(0, entry.Text.Length - "kg".Length);
                        }
                    }
                }
            };
```

![popupentry](https://user-images.githubusercontent.com/1029155/71565662-5c785c00-2af4-11ea-9fd2-7dd17a730140.gif)

**Comment by EmilAlipiev** [comment]
Cool. Looks like that it will work for me.
