### ISSUE TITLE
BackgroundImageSource not working on watchface xamarin.forms app

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#213]
I added a png into res folder and referenced directly like below. it works on a contentpage but not on circlepage why?
```

<Application.MainPage>
        <tz:CirclePage BackgroundImageSource="WatchFace.png">
            <StackLayout>
```

**Comment by myroot** [comment]
It seems to never working before. I update a patch to fix this issue
