### ISSUE TITLE
Putting labels on CircleProgressBar

### ISSUE THREAD

**Issue by TobiaApolloni** [Samsung/Tizen.CircularUI#216]
Hello,
thank you very much for your CircularUI, it has been a blessing for me.
I have to make a progress bar with a label on it, like this one:
![example](https://user-images.githubusercontent.com/34090592/71514198-d662d800-289d-11ea-8b3b-69f2de1a1f6a.png)

Are there plans to implement something like this in the near future?
Alternatively, how can i implement that in my project?

Thank you very much for you time!

**Comment by jkpu** [comment]
Hello, 
Tizen.CircularUI support Tizen native widget and layout for Tizen Xamarin.Forms app.
Tizen does not support label progress bar like as your screen shot(label position should move and bar color is gradient). and also we don't have plan to add this widget.
If you want to make this progress bar in your app, you should implement this using custom renderer using existing control and layout.
