### ISSUE TITLE
Failure to 'load detials' of project

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#217]
**Describe the bug**
It appears that there is some error in the project metadata which causes nuGet restore to fails.
Furthermore I cannot remove or install nuGets packages and given the following error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The operation failed as details for project Tizen.Wearable.CircularUI.Forms.Renderer could not be loaded.				

**To Reproduce**
1. Clone repository
2. attempt to restore nuget packages
3. attempt to build projects
4. See error:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Error occurred while restoring NuGet packages: The operation failed as details for project Tizen.Wearable.CircularUI.Forms.Renderer could not be loaded.				
Error	NETSDK1004	Assets file 'C:\Users\axa88\Git\Samsung\Tizen.CircularUI\src\Tizen.Wearable.CircularUI.Forms\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Tizen.Wearable.CircularUI.Forms	C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	234	
Error	NETSDK1013	The TargetFramework value 'tizen40' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.	Tizen.Wearable.CircularUI.Forms.Renderer	C:\Program Files\dotnet\sdk\3.1.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets	93	

**Expected behavior**
It would be expected that the archived projects could be built/run with minimal issue

**Screenshots**
If relavant, I find the project Target Framework blank and not already set.
![image](https://user-images.githubusercontent.com/13371986/71557632-a723a680-2a16-11ea-9789-8e9e44980ba7.png)

**Environment (please complete the following information):**
see project details

**Additional context**
Im a Tizen noob, perhaps I am missing something, or there is something haven't installed, but it is oblivious to me thus far.

**Comment by jkpu** [comment]
Hello
Did you install VisualStudio tool for Tizen? : https://developer.tizen.org/development/visual-studio-tools-tizen/installing-visual-studio-tools-tizen 
Tizen.Wearable.Circular.Forms.Renderer csproj TFM is 'tizen40' but your error log has following messege. 
"Error NETSDK1013 The TargetFramework value 'tizen40' was not recognized. "

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>tizen40</TargetFramework>
  </PropertyGroup>
```

**Comment by axa88** [comment]
Thank you for your reply.
I do believe i have the required tooling installed, namely:
- Visual Studio Tools for Tizen 3.1.0.0
- Visual Studio 2019 Version 16.4.2
Also seemingly required:
- Xamarin
(The about log copied below)

Using the above i can create Tizen wearable apps for v4 and v5 and seemingly v5.5 and run them in the emulator.
Of course I would like to be able to run the samples.
Surely it maybe a configuratoin issue, rather than a project issue, Im just unsure where to go with this.


```
- Microsoft Visual Studio Community 2019
Version 16.4.2
VisualStudio.16.Release/16.4.2+29613.14
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA502
Microsoft Visual C++ 2019

Arduino IDE for Visual Studio by Visual Micro   19.0
Visual Micro is an Arduino Compatible IDE for Visual Studio 2015-2019. For more information and forum please visit www.visualmicro.com.

ASP.NET and Web Tools 2019   16.4.457.38025
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.4.457.38025
Azure App Service Tools v3.0.0

C# Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.0 (d16-2@8b56e20)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

GitHub.VisualStudio   2.10.8.8132
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

JetBrains ReSharper Ultimate 2019.3   Build 193.0.20191207.64949
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2019 JetBrains, Inc.

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.0.87+gbb515bf382
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.5.24 (1fafd7e)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61912.09160
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.11031.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.4.1-beta4-19610-02+c4e5d138903b899477649a17f197abd2bcb22f9e
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.307 (d16-4@e031886)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.464 (remotes/origin/d16-4@4abf337c3)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.1.0 (d16-4/f2c9364)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: bef1e63
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b


Xamarin.iOS and Xamarin.Mac SDK   13.8.3.0 (0d8fe21)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
I can create 
```

**Comment by jkpu** [comment]
I have tried to build Tizen.Wearable.CircularUI.Forms.Renderer project with VS2019 16.4.2 and Visual Studio Tools for Tizen 3.1.0.0. but the build was succeeded and I can't reproduce your build error.

Which solution file did you used? 'Tizen.Wearable.CircularUI.sln" or 'Tizen.Wearable.CircularUI.Test.sln`
Please try to build 'WearableUIGallery.Tizen.Wearable in Tizen.Wearable.CircularUI.Test.sln

![capture](https://user-images.githubusercontent.com/31116585/71572907-9eb99180-2b24-11ea-807e-06c4d43a4dee.png)

Did you used `Tizen.Wearable.CircularUI.Forms.Renderer`  project for reference project for your sample app?

**Comment by axa88** [comment]
Yes.  I am (now) sure to use the project you indicate as the start up project and attempt the build.

![image](https://user-images.githubusercontent.com/13371986/71577882-e52ad400-2ac3-11ea-994c-30f713d05461.png)

Now that you menion the referance specifically, I see this is the issue.
As I mention before I can not restore or modify/add/remove/update any nuGet packages as VS seems to have a problem reading the project files as is.
Therefore all my referaces appear to be missing:

![image](https://user-images.githubusercontent.com/13371986/71578018-5ff3ef00-2ac4-11ea-9658-d67b7723da54.png)

I simply dont have any of these problems when creating a project from scratch:

![image](https://user-images.githubusercontent.com/13371986/71578191-21126900-2ac5-11ea-8f8e-98f3686c9951.png)

Thank you for your attention,
As your able to build I must assume this is a configuation problem, so please feel free to close the issue to keep things clean.
