### ISSUE TITLE
SvgCachedImage does it work?

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#219]
I followed the [docu](https://samsung.github.io/Tizen.NET/tizen.net/Image-caching-with-FFImageloading/#features-support-on-tizen) and it claims that svg support is working for Tizen,
But i cant make it work it. I tried using embedded image and under res folder as below but doesnt work at all for me. I am on tizen 4.0.

I added line

```
var app = new Program();
Forms.Init(app);
// Initialize FFImageLoading with FormsApplication object
FFImageLoading.Forms.Platform.CachedImageRenderer.Init(app);
```

```
 <ffimageloadingsvg:SvgCachedImage HorizontalOptions="EndAndExpand"
                                                             HeightRequest="24" WidthRequest="24"                                                            
                                                              Source="heart.svg" />
```

```
              <ffimageloadingsvg:SvgCachedImage HorizontalOptions="EndAndExpand"
                                                             HeightRequest="24" WidthRequest="24"                                                            
                                                              Source="resource://myApp.Icons.heart.svg" />
```

**Comment by jkpu** [comment]
Thanks you for your issue reporting 
your issue is not related Tizen.CircularUI. Except Tizen.CircularUI issue, please raise issue in [Tizen.NET github issue](https://github.com/Samsung/Tizen.NET/issues)

**Comment by EmilAlipiev** [comment]
Done here thanks https://github.com/Samsung/Tizen.NET/issues/49
