### ISSUE TITLE
Default layoutoption FillAndExpand?

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#220]
I have recognized that i have to set fillAndExpand for many Circular and xamarin layouts in Tizen watch development. Can we have that default if not set? I think that in xamarin.forms android is default.

**Comment by rookiejava** [comment]
Thank you for reaching out! According to the Xamarin.Forms's LayoutOption [guide](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/layouts/layout-options)
, the default value of a view's `HorizontalOptions` and `VerticalOptions` properties is `LayoutOptions.Fill`.
