### ISSUE TITLE
Add ability to disable CircleStepper wrap around

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#223]
**Is your feature request related to a problem? Please describe.**
It does not appear possible to prevent the CircleStepper from wrapping around between Min <> Max values.

**Describe the solution you'd like**
I would like to have available any way, perhaps a boolean property, which allows/prevents wrap around:
ex.
WrapAround = true/false;

**Describe alternatives you've considered**
Perhaps it is possible to record begin, end values and swipe direction, then determine if wrap around has occurred then manually snap the value back to Min/Max manually??
Native support would be much better than this.

**Additional context**
Here you can see it is possible to drag the stepper between min and max values:

![image](https://user-images.githubusercontent.com/13371986/72418405-c45fb100-3748-11ea-9ffc-41993b5e0d94.png)

Additionally it should be concidered how to display values when at Min or Max stepper positions.

When wrap around is disabled, when displaying Max value, it may be good to remove Min values from view.  becuase keeping Min values in view gives indication that wrap around is possible:

![image](https://user-images.githubusercontent.com/13371986/72418653-3cc67200-3749-11ea-9bca-b60b69a3a24c.png)

Reciprocally when wrap around is disabled, when displaying Min value, it may be good to remove Max values from view.  because keeping Max values in view gives indication that wrap around is possible:

![image](https://user-images.githubusercontent.com/13371986/72418966-e0178700-3749-11ea-9040-fcad0cdf903b.png)

Code used for example object above:

    `    var circleStepper = new CircleStepper
			{

				HeightRequest = 350,
				Title = "stepper",
				HorizontalOptions = LayoutOptions.Center,
				Increment = 1,
				LabelFormat = "%1.1f",
				Maximum = 100.0,
				Minimum = 0.0,
				Value = 50,
			};`

**Comment by jkpu** [comment]
Did you mean "wrap around" word that stepper value is in max value and then It can go min value ? 
(e.g  min 0, max 100,   100(max) -> drag ->  0 (min) -> drag-> 1  )
And you want to add  property for blocking this behavior ?

**Comment by axa88** [comment]
> 
> 
> Did you mean "wrap around" word that stepper value is in max value and then It can go min value ?
> (e.g min 0, max 100, 100(max) -> drag -> 0 (min) -> drag-> 1 )
> And you want to add property for blocking this behavior ?

Yes!
Isnt this a useful feature?

**Comment by jkpu** [comment]
I added new Property for your request(PR #224 ).  
If you set `IsWrapEnabled` to false, It will block wrap around over the max/min value.

When IsWrapEnabled property set True (Default value)
![CircleStepper_IsWrapped_true](https://user-images.githubusercontent.com/31116585/72428866-ecdfbd80-37d1-11ea-8b6b-e30d721e19f5.png)


When IsWrapEnabled property set False
![CircleStepper_IsWrapped_false](https://user-images.githubusercontent.com/31116585/72428868-efdaae00-37d1-11ea-9a19-958a430a559d.png)
