### ISSUE TITLE
PopupEntry, inability to see changes while Text edit view is active.

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#233]
**Describe the bug**

PopupEntry properties such as TextColor and PopupBackgroundColor are not changeable while the popup entry is visible.  Rather than an enhancement, i believe this is a bug.

Given the code below, i have a popup entry for a  user to enter a valid hostname.
While the user is entering text the input is validated.
If the text is valid, the text should be made green, if the text is invalid the text should be made red, but as can be seen, the color change is not applied until the keyboard/editor is closed.

It should be possible to verify and visually adjust the TextColor or PopupBackgroundColor color while a user is actively inputting text, but it is not currently possible to see these changes in the edit view, only after the editor/keyboard is closed.  This may appear to me a bug rather than an enhancement.

Note: this bug is only observed on emulator as i do not (yet) own real hardware.

```
private void OnListCellTap(Credentials credentials)
{
	var hostEntry = new PopupEntry
	{
		Margin = new Thickness(20, 0, 20, 0),
		HeightRequest = 65,
		HorizontalOptions = LayoutOptions.Fill,
		VerticalOptions = LayoutOptions.Fill,
		HorizontalTextAlignment = TextAlignment.Center,
		BackgroundColor = Color.Black,
		PopupBackgroundColor = Color.Black,
		ReturnType = ReturnType.Done,
	};
	hostEntry.TextChanged += (sender, args) =>
	{
		if (ValidHostname.IsMatch(hostEntry.Text))
		{
			hostEntry.TextColor = Color.Green;
			hostEntry.BackgroundColor = Color.Black;
		}
		else
			hostEntry.TextColor = Color.Red;

		hostEntry.BackgroundColor = string.IsNullOrWhiteSpace(hostEntry.Text) ? Color.Red : Color.Black;
	};

	hostEntry.Text = credentials.Name;
			
	_profileEditView = new StackLayout
	{
		Padding = new Thickness(20, 30, 20, 20),
		Margin = new Thickness(20, 20, 20, 20),
		Children = { hostEntry }
	};

	Content = _profileEditView;
}
```

**To Reproduce**
1. start a edit text with a valid text, here we see the color green
![image](https://user-images.githubusercontent.com/13371986/75096724-5c369300-5570-11ea-89ae-5c476a163682.png)

2. Then edit the test with an invalid character, on text apply a text color change.
3. Observe the text change does not apply in the edit view.
![image](https://user-images.githubusercontent.com/13371986/75096775-e1ba4300-5570-11ea-991a-c4b1810977a3.png)

4. Immediatly close the editor and then see the color change applied.
![image](https://user-images.githubusercontent.com/13371986/75096787-fd254e00-5570-11ea-9bb7-114251bfd73b.png)

Note that the same is true for PopupBackgroundColor, changes to it while editor/keyboard active are not observed until the editor/keyboard is closed and then re opened, so observing the changes is not only 1, but 2 steps away.

**Expected behavior**
It is expected that changes to TextColor and PopupBackgroundColor are applied during edit view as they are direct properites of that view.

**Screenshots**
see above

**Environment (please complete the following information):**
 - Target Product:
![image](https://user-images.githubusercontent.com/13371986/75096824-5db48b00-5571-11ea-8b83-0f9fcb7d37c6.png)

 - Tizen Platform Version:
 4.0.0
 - Tizen.CircularUI Version:
1.4.0

**Additional context**
On a related note:
Android specifically separates the Hint, Displayed and Changing text properties of an EditText object.
While i dont see the pressing need to separate the displayed and changing text, adding a PopupEntry object Hint property seems like a nice enhancement.

**Comment by jkpu** [comment]
This issue was fixed in https://github.com/Samsung/Tizen.CircularUI/pull/239 , and will be included next nuget release

**Comment by EmilAlipiev** [comment]
is there any date for next release?

**Comment by jkpu** [comment]
We will release new NuGet package at early of March.

**Comment by EmilAlipiev** [comment]
awesome. thats good to hear. i hope that you can get a new tizen.net extension on visual studio also. it is pretty buggy and impossible to work with.

**Comment by axa88** [comment]
> 
> 
> awesome. that's good to hear. i hope that you can get a new tizen.net extension on visual studio also. it is pretty buggy and impossible to work with.

Come on now, its not that bad.

Indeed I recall there are some ambiguous processes to follow when first installing the tool chain.
But this link has quite clear instructions:
[Installing Visual Studio Tools for Tizen](https://docs.tizen.org/application/vstools/install)

Also Ive had some challenges using older samples with the latest releases, and often need to manually edit the proj files.

But otherwise I find it a pleasure to use.
Not to mention the turn around time fixing and addressing issue is remarkable.

**Comment by EmilAlipiev** [comment]
I dont have installing or running. i even built apps with tizen.net but there is usually difference between emulator and watch, it is pretty annoying. my app works an emulator and crashes on the watch. I dont get any information on debugger and need to search within the logs. Logs are even sometimes not very helpful. Breakpoints are often not hitting. I am still not able to use SAP on my emulator.
I mean that i love tizen and samsung development and i wish them to do some improvements on visual studio by working with microsoft team closer

**Comment by axa88** [comment]
Yes there is weakness in debugging for sure.  I hope to have the time to look into or report issues someday.

I think the one that bothers me the most in these early stages:
1. source line debugging does not always give you clear information about your variables.
2. unhanded exceptions trickle up as a 'segmentation fault' in main application with no inner exceptions or information given otherwise.
This can be VERY hard to debug when for example exceptions is thrown during api use such as `Preferences`  you will be given no indication what or where something is going wrong.

I understand.
