### ISSUE TITLE
how to display circled list like apps on the watch

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#234]
i want to display a list like Circlepage+ moreoption but using toolbaritem, list is hidden and only displayed after clicked 2 dots. Is it possible to get the list like apps view on galaxy watch? so when i come to the page, that list is already displayed. I dont know if it is another view or it is using more option?

![image](https://user-images.githubusercontent.com/10422347/75121589-bf6e1580-5695-11ea-9e7c-7714e8cef2f0.png)

**Comment by sondavide** [comment]
@EmilAlipiev  I used ElmSharp to do the RotarySelector UI. It does not exist another way yet

**Comment by rookiejava** [comment]
Sorry for late response. 🙏 
As @sondavide mentioned above, in the Tizen 4.0 or earlier version, Native UI Framework (called EFL) provides a Rotary Selector for use with the More Option. However, as platform is evolved and the OneUI is newly introduced, existing Rotary Selector has not been decided whether it can be maintained in the future. This is why we don't provide Rotary Selector as a separate View in CircularUI. If there us any change in our policy, I'll get back to you. Thanks !

**Comment by tomh4** [comment]
Has something changed about this?
I managed to get the RotarySelector working, but I cant figure out a decent way to colorize the icons or even keep them simply white.
