### ISSUE TITLE
How to override default keyboard layout in Galaxy Watch?

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#240]
when i use numeric keyboard on entry and if my language is German, it should display comma instead of dot as comma separator. But when entry is opened, it displays always dot. This is a known issue for Samsung phones also. I am able to override the default keyboard in android like below.
how can i achieve this in Tizen watch?

```
   this.Control.KeyListener = Android.Text.Method.DigitsKeyListener.GetInstance(string.Format("1234567890{0}", Settings.CurrentCultureInfo.NumberFormat.CurrencyDecimalSeparator));
            this.Control.InputType = Android.Text.InputTypes.ClassNumber | Android.Text.InputTypes.NumberFlagDecimal;
```

PS; i have created this issue here https://github.com/Samsung/Tizen.NET/issues/57 but i realized that maybe it is more circularUI issue. please feel free to close one of them :)

**Comment by myroot** [comment]
It is a issue of on-screen keyboard app on device.
Keyboard app should determine a kind of decimal separator according to locale information. 
App only can set layout of keyboard. app should not set details like a decimal separator.

Anyway, We can't override a keyboard layout details
