### ISSUE TITLE
PopupEntry, neither Focused nor Unfocused events can be triggered

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#246]
**Describe the bug**
Neither the `Focused` nor `Unfocused` events trigger for a `PopupEntry` object.

**To Reproduce**
1. create a popup object
2. assign the `Focused` and/or `Unfocused` event
3. observe by any means, breakpoint/application code, that the event handler is never executed

Example Code:

```
_nameEntry = new PopupEntry
{
	HeightRequest = 65,
	HorizontalOptions = LayoutOptions.FillAndExpand,
	VerticalOptions = LayoutOptions.Center,
	FontAttributes = FontAttributes.Bold,
	HorizontalTextAlignment = TextAlignment.Start,
	BackgroundColor = Color.Black,
	PopupBackgroundColor = Color.Black,
	ReturnType = ReturnType.Done,
	IsTextPredictionEnabled = true
};

_nameEntry.TextChanged += (sender, args) =>
{
	// this handler triggers
};

_nameEntry.Focused += (sender, args) =>
{
       // this handler DOES NOT trigger
	var v = _nameEntry.Text;
	_nameEntry.Text = "focus trigger";
};

_nameEntry.Unfocused += (sender, args) =>
{
        // this handler DOES NOT trigger
	var v = _nameEntry.Text;
        _nameEntry.Text = "unfocus trigger";
};
```

**Expected behavior**
An expectation that any event available of the `PopupEntry` is triggered and executes the event handler code.

**Environment:**
 - Target Product Emulator 4.0 Release on 3.6 SDK (2.8.0.24)
 - Tizen Platform Version [Tizen 4.0.0]
 - Tizen.CircularUI Version [1.4.0]

   

**Additional context**
I am seeking a way to cancel `PopupEntry Text` property changes.
There is already the Return Button to apply changes, I would like to find a way to cancel changes using the Back Button.  My idea is to cache the text before entering the edit mode, and replace the text if the Back Button is pressed.
To do this I need to detect before and/or after the `PopupEntry` edit mode is activated.

Note target being emulator, this has not been tested on hardware.

**Comment by myroot** [comment]
Actually, PopupEntry create a Popup, so entry's focus is lost by popup. Alternatively, you can use `IsPopupOpened` property.

Please refer this issue
https://github.com/Samsung/Tizen.CircularUI/issues/212

**Comment by axa88** [comment]
I believe i can use workaround provided in linked issue. thanks
