### ISSUE TITLE
`OnBackButtonPressed` override of a `CirclePage` does not execute while a `PopupEntry` edit mode is active

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#247]
**Describe the bug**
`OnBackButtonPressed` override of a `CirclePage` does not execute a while `PopupEntry` edit mode is active.

**To Reproduce**
1. Instantiate a page inheriting from a `CirclePage`
2. Instantiate a `PopupEntry` object
3. Navigate to `PopupEntry` and activate the entry edit mode
4. Press Back Button
5. Observe via breakpoint/app code that `OnBackButtonPressed` method does not execute

**Expected behavior**
It is expected that the `OnBackButtonPressed` method of a `CirclePage` will execute even while the edit mode of a `PopupEntry` is active.

Otherwise a way to handle the back button when `PopupEntry` edit mode is active should be provided.

**Environment:**
 - Target Product Emulator 4.0 Release on 3.6 SDK (2.8.0.24)
 - Tizen Platform Version [Tizen 4.0.0]
 - Tizen.CircularUI Version [1.4.0]

**Additional context**
I am seeking a way to cancel `PopupEntry Text` property changes.
There is already the Return Button to apply changes, I would like to find a way to cancel changes using the Back Button.  My idea is to cache the text before entering the edit mode, and replace the text if the Back Button is pressed.  For this Back button handling is needed while the edit mode is active.

Note target being emulator, this has not been tested on hardware.

**Comment by myroot** [comment]
You need to understand event propagation mechanism. 
If top most element was consume event, does not propagate to below element.
in this case, Popup was consume BackButton event, so CirclePage was not invoked OnBackButtonPressed

**Comment by axa88** [comment]
> You need to understand event propagation mechanism.

I can try to understand event propagation mechanism, but it would help for you to try and understand base issue before hastaliy closing.

Main point of issue was to report it appears not possible to detect Back Button Pressed while while PopupEntry IsPopupOpened = true.

If this is invalid and should be closed, please suggest how it is possible to detect back button pressed while PopupEntry is active.

**Comment by myroot** [comment]
First, We do not allow overriding of Back Button behavior of Popup
You can observing time of closing popup by using `IsPopupOpened` property like below
``` c#
entry.PropertyChanged += (s, e) => {
   if (e.PropertyName == "IsPopupOpened") {
      if (entry.IsPopupOpened) {
         // code for Popup is opening
      } else {
         // code for Popup is closing
      }
   }
};


```

**Comment by axa88** [comment]
> You can observing time of closing popup by using `IsPopupOpened` property like below

Yes, i just came to reply when i realized workaround of #212 is valid here also. thanks for the help

**Comment by axa88** [comment]
> Yes, i just came to reply when i realized workaround of #212 is valid here also. thanks for the help

Im mistaken, unfortunately workaround does not tell me that Back Button is the _reason_ the popup entry has closed.

What i am seeking a way to rollback changes to text when the back button is the cause of edit popup was close.

If there is any work around for this, please let me know, otherwise I would believe it is a valid issue.

**Comment by axa88** [comment]
Attempting to workaround to set flag using `PopupEntry ReturnCommand` to set flag that text is intended to be saved (when closed by Return Button) or not saved (when closed by Back Button):

```
_nameEntry = new PopupEntry
{
	ReturnType = ReturnType.Done,
	ReturnCommand = Save,
};
```

Then using `PopupEntry ReturnCommand` to set flat that text is intended to be saved.

```
private static bool _save;
private Command Save { get; } = new Command(() => _save = true);
```

Then use propety change event to detect when popup is closed or opened.

```
_nameEntry.PropertyChanged += (sender, args) =>
{
	if (args.PropertyName == "IsPopupOpened")
	{
		if (_nameEntry.IsPopupOpened)
		{
			_save = false;
			_undo = _nameEntry.Text;
		}
		else
		{
                     if (!_save)
                         _nameEntry.Text = _undo;
                    else
                         _save = false;
                }
	}
};
```

But this does not work becuase `PropertyChanged` event is called _before_ `ReturnCommand` is executed.

Still looking for workaround

**Comment by axa88** [comment]
Adding timer to delay reading of flag appears to be a workaround.

```
_timer = new Timer(state =>
{
	if (!_save)
		_nameEntry.Text = _undo;
	else
		_save = false;
});
```

Then adjusting PropertyChange event handler

```
_nameEntry.PropertyChanged += (sender, args) =>
{
	if (args.PropertyName == "IsPopupOpened")
	{
		if (_nameEntry.IsPopupOpened)
		{
			_save = false;
			_undo = _nameEntry.Text;
		}
		else
			_timer.Change(100, Timeout.Infinite);
	}
};
```

But frankly this workaround is not elegant; entirely too much work, too verbose, and with seemingly too much overhead as there are many PropertyChange events triggering.

**Comment by myroot** [comment]
It seem to try rollback a text when on-screen keyboard is closing by back-key. it is difficult as you know and It also hard to implement on others platform. 

It is workaround code, I hope working for you
``` c# 
    class CommittedPopupEntry : PopupEntry
    {
        string committed = string.Empty;
        public CommittedPopupEntry()
        {
            PropertyChanged += OnPropertyChanged;
            Completed += OnCompleted;
        }

        void OnCompleted(object sender, EventArgs e)
        {
            committed = Text;
        }

        void OnPropertyChanged(object sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(IsPopupOpened))
            {
                if (IsPopupOpened)
                {
                    committed = Text;
                }
                else
                {
                    Device.BeginInvokeOnMainThread(() =>
                    {
                        Text = committed;
                    });
                }
            }
        }
    }
```

**Comment by myroot** [comment]
![popupentry](https://user-images.githubusercontent.com/1029155/75644243-f8ede480-5c84-11ea-9b33-e1554ad9773b.gif)

**Comment by axa88** [comment]
This works and more elegant than my solution. i was not aware of `BeginInvokeOnMainThread` method., thank you
