### ISSUE TITLE
Button with either Background Color set Black or Transparent has an actively pressed color of default blue

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#253]
**Describe the bug**
The actively clicked background color of a `Button` is relative to its `BackgroundColor`:

ex: `BackgroundColor = Color.DarkOrange`

Not pressed:
![image](https://user-images.githubusercontent.com/13371986/76147747-7478d880-606d-11ea-8edf-7f90c6ad294b.png)

Pressed:
![image](https://user-images.githubusercontent.com/13371986/76147770-b9047400-606d-11ea-9875-cbeee8a31551.png)

But when the `Button` has set either `BackgroundColor = Color.Black` or `BackgroundColor = Color.Transparent` the actively pressed color is `Color.Default` a sort of blue:

Not pressed:
![image](https://user-images.githubusercontent.com/13371986/76147819-15679380-606e-11ea-961a-94e10e0d809c.png)

Pressed:
![image](https://user-images.githubusercontent.com/13371986/76147832-4a73e600-606e-11ea-865e-b60f78e12d61.png)

Id rather mark this as enhansment than a bug but unsure how to do so.

**To Reproduce**
1. Create a `Button`, give it a `BackgroundColor` of  `Color.Black` or `Color.Transparent` 
2. Click on it
3. Notice that the clicked background is that of `Color.Default` and that doesn't necessarily correspond to black/transparent

**Expected behavior**
It is expected that either a more more aesthetically relative color is chosen for these 2 background colors or provide a way for the user to set them.
Perhaps a shade of gray for the `Color.Black`.
Perhaps no color set for `Color.Transparent` (keep it Transparent)

**Environment:**
    Target Product Emulator 4.0 Release on 3.6 SDK (2.8.0.24)
    Tizen Platform Version [Tizen 4.0.0]
    Tizen.CircularUI Version [1.4.0]

**Additional context**
This is noticeable when attempting to set a color theme to your objects.
A black/transparent theme is infused with blue which seems out of place

**Comment by jkpu** [comment]
Thanks you for your issue reporting.
I have checked backend(Elmsharp.Button) of CircularUI. There is no way to set button pressed Color.
And default(dark blue) color is native backend behavior. this is not CircularUI's renderer's behavior.
native backend can't be updated because this emul and watch device is already released.
This issue is restriction of native, so I recommand you to use another button color instead of black and transparent.

**Comment by axa88** [comment]
Yes sometimes changes are not feasible.  Thanks for investigating the issues

**Comment by bangfutao** [comment]
I have the same problem, the changes are not feasible either. Users have to live with it unfortunately. 
https://github.com/Samsung/Tizen.CircularUI/issues/345
