### ISSUE TITLE
CircleDateTimeSelector date label does display incorrectly.

### ISSUE THREAD

**Issue by flyofsky** [Samsung/Tizen.CircularUI#256]
**Describe the bug**
CircleDateTimeSelector date label does display incorrectly.

**Screenshots**
![DatePicker_bug](https://user-images.githubusercontent.com/16184582/76396775-2d684b80-63bd-11ea-9fb5-f2ad15217f62.png)

**code.xaml**
```xml
<?xml version="1.0" encoding="utf-8" ?>
<c:CirclePage
    x:Class="DatePicker.Views.DatePickerPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:c="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms">
    <c:CircleDateTimeSelector />
</c:CirclePage>
```

**code.xaml.cs**
```C#
public partial class DatePickerPage : CirclePage
    {
        public DatePickerPage()
        {
            InitializeComponent();
        }
    }
```

Binary : tizen-4.0-unified_20200304.1
https://download.tizen.org/snapshots/tizen/4.0-unified/tizen-4.0-unified_20200304.1/images/emulator/wearable-emulator-circle/

**Comment by jkpu** [comment]
This issue is only reproduced in shell

**Comment by jkpu** [comment]
When I had test with your test code. I can fix with only changing Applicaton ID and package name. 
before DatePicker  => after org.tizen.DatePicker 

[after change app ID and package name from Datepicker -> org.tizen.DatePicker ]
![Uploading W-4.0-circle-x86-preview-2020-03-13-162340.png…]()

after tizen-manifest.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest package="org.tizen.DatePicker" version="1.0.0" api-version="4" xmlns="http://tizen.org/ns/packages">
    <profile name="wearable" />
    <ui-application appid="org.tizen.DatePicker" exec="DatePicker2.dll" multiple="false" nodisplay="false" taskmanage="true" type="dotnet" launch_mode="single">
        <label>org.tizen.DatePicker</label>
        <icon>DatePicker.png</icon>
        <metadata key="http://tizen.org/metadata/prefer_dotnet_aot" value="true" />
        <splash-screens />
    </ui-application>

```


Maybe this issue  Tizen FW restriction or bug, I will ask this issue to person in charge.
