### ISSUE TITLE
Swipe down from Header of CircleListView towards list area causes OnBackButtonPressed event trigger

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#257]
**Describe the bug**

When swiping down at various points from the Header area, on a `CircleListView` of a `CirclePage`, the `OnBackButtonPressed` event is triggered.

The CircleList:

```
ListView = new CircleListView
 {
	 Header = new Label
	 {
		 FontSize = 20,
		 FontAttributes = FontAttributes.Bold,
		 VerticalOptions = LayoutOptions.Center,
		 HorizontalOptions = LayoutOptions.Center,
		 HorizontalTextAlignment = TextAlignment.Center,
		 TextColor = Color.Default,
		 Text = "Homes 🏘️",
	 },
	 BarColor = Color.Default,
	 ItemTemplate = new DataTemplate(typeof(TViewCell)),
	 ItemsSource = new ProfileViewModel(profiles).ItemCollection,
 };

 Content = ListView;
```

There are no other swipe or gesture recognizer in use.

**To Reproduce**
1. Create `CircleListView` similar to the above
2. Click on top of `Header` area near or close to an outside edge
3. Swipe down towards the list area
4. See `OnBackButtonPressed` event gets triggered

**Expected behavior**
It is expected that swiping on the viewable area does not unexpectedly trigger such a method

**Screenshots**
![SwipeTriggersOnBackButtonPressed](https://user-images.githubusercontent.com/13371986/76674160-977e1d80-6582-11ea-8850-db45a88c6208.gif)

**Environment :**
Target Product Emulator 4.0 Release on 3.6 SDK (2.8.0.24)
Tizen Platform Version [Tizen 4.0.0]
Tizen.CircularUI Version [1.4.0]

**Additional context**
No available hardware to test, this is odd behavior is noticed in emulator.
May not be Circular UI problem, perhaps only emulator.

**Comment by myroot** [comment]
Hi, Thanks for reporting error, 
It is platform default behaivor (Bezel Swipe Down (Back))
https://developer.tizen.org/design/wearable/ux-overview/gestures?langredirect=1

But, Product device is not following this behavior

**Comment by axa88** [comment]
Interesting.

I wonder how this will work with [SwipeRefresh](https://developer.tizen.org/design/wearable/patterns/swipe-refresh?langswitch=en) 

With so little real estate on wearable device display perhaps this behavior should have way to be disabled.

**Comment by axa88** [comment]
@myroot 

I would think this is valid bug becuase as you say wearable Product does not follow Platform behavior, therefore wearable emulator should follow Product behavior not platform behavior.

Is there a public repo for the emulator bugs i could report this?

Unfortunatly when i demonstrate this application online for client they see it as unstability rather than acceptible behavior  :(

**Comment by myroot** [comment]
@axa88 
I think, The key factor to determining a bug is that is intended or not.
Swipe gesture and BackButton pressed event is intended behavior on platform

**Comment by myroot** [comment]
@axa88 
You can report a bug on here
https://www.tizen.org/community/bug-tracker/how-report-bugs
