### ISSUE TITLE
Crash when CircleDateTimeSelector is set on ContentPage

### ISSUE THREAD

**Issue by flyofsky** [Samsung/Tizen.CircularUI#268]
**Describe the bug**
Crash when CircleDateTimeSelector is set on ContentPage

Crash
```c#
public partial class DatePickerPage : ContentPage
    {
        public DatePickerPage()
        {
            InitializeComponent();
            Content = new StackLayout
            {
                Children =
                {
                    new CircleDateTimeSelector()
                }
            };
        }
    }
```

Working well
```c#
public partial class DatePickerPage : CirclePage
    {
        public DatePickerPage()
        {
            InitializeComponent();
            Content = new StackLayout
            {
                Children =
                {
                    new CircleDateTimeSelector()
                }
            };
        }
    }
```

**Comment by jkpu** [comment]
CircleDatatime only can work in CirclePage. please refere to CircularUI guide.

https://samsung.github.io/Tizen.CircularUI/guide/CircleDateTimeSelector.html

WARNING: CircleListView, CircleDateTimeSelector, CircleScrollView, CircleStepper must be confined in the CirclePage container or Page with CircleSurfaceEffectBehavior. If you add these controls in any other way, it may cause an exception or cannot display the controls.
