### ISSUE TITLE
Setting the Width of a PopupEntry appears to truncate rather than resize the object

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#277]
**Describe the bug**
Setting the Width of `PopupEntry` is expected to resize the object, but rather it appears to only truncate the viewable area.

As one result, the problem is manifested in the example below.

- The `HorizontalTextAlignment` of truncated `PopupEntry` will no longer function as expected.

- It is difficult to manage the position and viewability of text of a PopupEntry.

**To Reproduce**
When attempting to create a Popup Entry next to another object, (a label in this example), the 2 items are placed inside of a `CircleStackLayout` (or `StackLayout`) in order to keep the objects side by side using property `Orientation = StackOrientation.Horizontal`.

Then the following code is placed inside of a Parent CircleStackLayout and set as the Content of a `CirclePage` and produces the expected result:

```
new CircleStackLayout
 {
	 Orientation = StackOrientation.Horizontal,
	 Children =
	 {
		 new PopupEntry
		 {
			 HorizontalOptions = LayoutOptions.Center,
			 HorizontalTextAlignment = TextAlignment.Start,
			 //WidthRequest = 150,
			 Text = "start alignment"
		 },
		 new Label { VerticalTextAlignment = TextAlignment.Center, Text = "label" },
	 }
 },
 new CircleStackLayout
 {
	 Orientation = StackOrientation.Horizontal,
	 Children =
	 {
		 new PopupEntry
		 {
			 HorizontalOptions = LayoutOptions.Center,
			 HorizontalTextAlignment = TextAlignment.End,
			 //WidthRequest = 150,
			 Text = "end alignment"
		 },
		 new Label { VerticalTextAlignment = TextAlignment.Center, Text = "label" },
	 }
 },
```

![image](https://user-images.githubusercontent.com/13371986/79822717-da8c9700-835f-11ea-9ed3-a62ab171c412.png)

But as can be seen the stack is too wide to fit on screen, therefore attempting to reduce the width of the `PopupEntry` by including property `WidthRequest = 150`.

But now the alignment appears incorrect:

![image](https://user-images.githubusercontent.com/13371986/79822991-83d38d00-8360-11ea-8524-3826d93f82f2.png)

It is expected that the **beginning** of the top Entry **"start...."** and and the **end** of the lower Entry **"....alignment"** is viewable but they are not.  No matter which alignment is selected, the text does not appear as expected, presumably because the `WidthRequest` truncates the viewable area rather than truly resizing it.

(Height/Vertical issues were not tested)

1. Include the above code in a parent `CircleStackLayout` then setting it to the content of a `CirclePage`

**Expected behavior**
See above

**Screenshots**
See above

Environment :
Target Product Emulator Version: 4.0 Release on 3.7 SDK (2.8.0.24)
Tizen Platform Version [Tizen 4.0.0]
Tizen.CircularUI Version [1.4.0]

Additional context
No available hardware to test, this is behavior is found in emulator.

**Comment by jkpu** [comment]
Thank you for issue reporting.
When I have test with your code snippet. I found following behavior or issue



- In first Image, I can only see the issue that label is not shown.
  CircleStackLayout  resize chidren's width or height, but not guarantee each children's width ratio. so label was removed and PopupEntry was truncated by CircleStackLayout renderer.
CircleStackLayout  is experimental layout API. so there are many unexpected behavior. This API was recommanded only one object for each orientation same as the test case in WearableUIGallery.
So I recommand you to use StackLayout instead of CircleStackLayout in your app.

![image](https://user-images.githubusercontent.com/31116585/79830353-30088880-83e0-11ea-8115-34fe4f99cec2.png)

- In second Image, this issue is not releated PopupEntry, `ellipsis` is not support in Entry and Popup Entry 

![image](https://user-images.githubusercontent.com/31116585/79831007-8f1acd00-83e1-11ea-8825-6d6ff1b6a757.png)

You can check with changing PopupEntry to Entry in your code. The Entry also show same text.
following images is behavior of Entry with `WidthRequest = 150`.  Even if  you change `WidthRequest`, entry's place holder label size is not changed.  place holder label  was only truncated 

![StackLayout_Entry](https://user-images.githubusercontent.com/31116585/79830229-f899dc00-83df-11ea-93dd-30f0805ffcb8.png)

**Comment by axa88** [comment]
@jkpu 
Yes first example image was only intended to compare to second example.  I believe first image is correct functionality, not a problem.
I also understand I should use only single object within rack stack layout.


So in your 2nd example image, text alignment is incorrect just as my second example image.  Therefore I believe your may be missing the point of the report.

In both our examples we use Start Alignment so it should show the BEGINNING of the text ex: "start...."
 And end alignment should show the END of the text. ex: ".... alignment"
Please look again, the results are exactly the OPPOSITE of what both our examples are showing!

Thank you for quick reply, but I wish you wouldn't close issues before any discussion can be made.

**Comment by jkpu** [comment]
I understand what is issue exactly.  
Text alignment in Entry with small `WidthRequest`  have wrong behavior. It seems like Tizen X.F Entry Renderer issue. I will report  this issue to proper person in charge
following image and code show Label alignment is correct with truncated object. but Entry is wrong behavior.

![W-4 0-circle-x86-preview-2020-04-21-161230](https://user-images.githubusercontent.com/31116585/79836707-7dd6be00-83eb-11ea-9533-b8f53b18ff52.png)



```C#
            MainPage = new CirclePage
            {
                Content = new StackLayout
                {
                    Orientation = StackOrientation.Vertical,
                    HorizontalOptions = LayoutOptions.CenterAndExpand,
                    Children =
                    {
                        new StackLayout
                        {
                            Orientation = StackOrientation.Horizontal,
                            Children =
                            {
                                new Entry
                                {
                                    HorizontalOptions = LayoutOptions.Center,
                                    HorizontalTextAlignment = TextAlignment.Start,
			                        WidthRequest = 150,
			                        Text = "start alignment",
                                },
                                new Label
                                { 
                                    VerticalTextAlignment = TextAlignment.Center,
                                    Text = "labeltest",
                                    WidthRequest = 50,
                                    HorizontalTextAlignment = TextAlignment.Start,
                                    HorizontalOptions = LayoutOptions.CenterAndExpand,
                                },
                            },
                        },
                        new StackLayout
                        {
                            Orientation = StackOrientation.Horizontal,
                            Children =
                            {
                                new Entry
                                {
                                    HorizontalOptions = LayoutOptions.Center,
                                    HorizontalTextAlignment = TextAlignment.End,
			                        WidthRequest = 150,
			                        Text = "end alignment"

                                },
                                new Label 
                                { 
                                    VerticalTextAlignment = TextAlignment.Center,
                                    Text = "labeltest",
                                    WidthRequest = 50,
                                    HorizontalTextAlignment = TextAlignment.End,
                                    HorizontalOptions = LayoutOptions.CenterAndExpand,
                                },
                            }
                        }
                    }
                }
            };
```

**Comment by axa88** [comment]
> Label alignment is correct with truncated object. but Entry is wrong behavior

Yes, that is the issue, entry alignment behavior is incorrect.  Perhaps issue title should be updated to reflect issue more precisely?

**Comment by myroot** [comment]
`HorizontalTextAlignment` property is only meaningful working when text block was smaller than Entry
In this case text block was bigger than Entry, so `HorizontalTextAlignment` was not working propertly.
It is limitation of Entry

**Comment by axa88** [comment]
@myroot 

> `HorizontalTextAlignment` property is only meaningful working when text block was smaller than Entry

I respectfully disagree.  Text Alignment is even MORE meaningful when text block is LARGER than Entry because when text is too large for entry you want more control of what user can see.  In this case it can be a requirement to understand what text is.
When text block is smaller than Entry, you can always see full text so in this case it is merely making layout more pretty, not as important.

Also even if you shrink font smaller to fit text block inside entry, the alignment problem can cause all text to not be in view!!  You cant see large text, you cant see small text... what is solution?

> In this case text block was bigger than Entry, so `HorizontalTextAlignment` was not working propertly.
> It is limitation of Entry

Is this actually an Entry _limitation_  or an Entry _bug_ ?
Notice when text block is larger than Entry, using Start and End Alignment produces different results!  End alignment appears how Start alignment should appear, and Start alignment looks how End alignment should appear.  To me this appears more like bug than limitation.


I understand you are convinced there may not be any fix, but perhaps it might be encouraging to keep bug open a bit longer for discussion to be made?

**Comment by myroot** [comment]
@axa88  Your requirement is more proper to `LineBreakMode` 
https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.linebreakmode?view=xamarin-forms

But it now only support on Label, We can consider support `LineBreakMode` on Entry

**Comment by myroot** [comment]
> when text is too large for entry you want more control of what user can see.

Yes, Entry provide scrolling Text block when text was larger than entry, User can swipe entry to scroll text

**Comment by axa88** [comment]
@myroot 

> Yes, Entry provide scrolling Text block when text was larger than entry, User can swipe entry to scroll text

Is there 'swipe entry to scroll' in Label as well?
I don't get this functionality on my Label implementation in emulator.
Or is there there limitation to this functionality on Label in emulator?

**Comment by myroot** [comment]
@axa88 
`Label` was not support scrolling, Only `Entry` is support it, but `Label` has LineBreakMode
