### ISSUE TITLE
[Bug] CircleSliderSurfaceItem not show

### ISSUE THREAD

**Issue by guangoon** [Samsung/Tizen.CircularUI#278]
**Description**
**when I use CircleSliderSurfaceItem to develop wearable app, But CircleSliderSurfaceItem not show**
## xaml:
<w:CirclePage.CircleSurfaceItems>
    <w:CircleSliderSurfaceItem
        x:Name="slider"
        Increment="0.5"
        Maximum="15"
        Minimum="0"
        BarRadius="80"
        IsVisible="True"
        BackgroundColor="Black"
        BackgroundLineWidth="15"
        BackgroundRadius="70"
        BarColor="Red"
        BarLineWidth="15"
        Value="3" />
</w:CirclePage.CircleSurfaceItems>
**To Reproduce**
1. Run app to show  CircleSliderSurfaceItem

**Expected behavior**
The CircleSliderSurfaceItem can normal display

**Screenshots**

**Environment (please complete the following information):**
 - Target Product [ Galaxy Watch]
 - Tizen Platform Version [Tizen 5.5]
 - Tizen.CircularUI Version [1.5.0]

**Additional context**

**Comment by jkpu** [comment]
Thank you for your issue reporting.
I have question about the issue. Did you add `RotaryFocusObject` in CirclePage ?

```xml
<w:CirclePage
    x:Class="WearableUIGallery.TC.TCCircleSliderSurfaceItem1"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
    RotaryFocusObject="{x:Reference slider}">
```

If you can add your XAML code and screen capture image. it will be helpful to resolve this issue.

**Comment by guangoon** [comment]
when add RotaryFocusObject="{x:Reference slider}", the CircleSliderSurfaceItem can show successful.
Thank you~
