### ISSUE TITLE
Ability to force to or select particular keyboard layouts of PopupEntry

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#280]
**Describe the bug/enhancement**
`PopupEntry` provides 5 keyboard layouts, but it would be useful to provide a way to force display of a particular layout upon opening.

For example, i have only numeric input so i would like to go to numeric input first..

Also it would be very useful to provide a way to limit the available keyboard layouts to only 1 or only a selected few.  Often all 5 layouts are undesireable 
I do not see anyway to do this.

I seed issue #240 and understand there is no way to override keyboard layout, but perhaps there is a way to enhance current functionality. 

**Expected behavior**
Expected to be able to streamline the use of the keyboard input interface

Environment :
Target Product Version: 4.0 Release on 3.7 SDK (2.8.0.24)
Tizen Platform Version [Tizen 4.0.0]
Tizen.CircularUI Version [1.4.0]

**Comment by jkpu** [comment]
If you want to open popup entry with numeric keybord, you just set Keyboard = "Numeric" in Xaml or behind code.

```xml
                <w:PopupEntry
                    AutomationId="popupEntry5"
                    HorizontalOptions="FillAndExpand"
                    VerticalOptions="CenterAndExpand"
                    Keyboard="Numeric"
                    HorizontalTextAlignment="Center"/>
```
