### ISSUE TITLE
CircleSliderSurfaceItem can not hide

### ISSUE THREAD

**Issue by guangoon** [Samsung/Tizen.CircularUI#281]
**Describe the bug**
 when Enter a page, we need slider is invisible, and press volume button, the slider is visible.
but slider always visible.
 <views:CirclePageEx
    x:Name="PlaybackPage"
    x:Class="VoiceMemo.Views.PlayBackPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:converters="clr-namespace:VoiceMemo.Converters;"
    xmlns:views="clr-namespace:VoiceMemo.Views;"
    xmlns:vm="clr-namespace:VoiceMemo.ViewModels;"
    xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
    RotaryFocusObject="{x:Reference VolumeProgress}">
    <w:CirclePage.CircleSurfaceItems>
        <w:CircleProgressBarSurfaceItem 
            x:Name="PlayProgress"
            BackgroundColor="#803011"
            BarColor="#ED1C23"
            Value="{Binding PlayingProcess}" />
        
        <w:CircleSliderSurfaceItem
            x:Name="VolumeProgress"
            BackgroundColor="#002A4D"
            BarColor="#008CFF"
            IsVisible="{Binding VolumeViewVisible}"
            Value="{Binding VolumeLevelProcess}"/>
    </w:CirclePage.CircleSurfaceItems>

**To Reproduce**
1. Go to play record page.
2. Click volume button

**Expected behavior**
when enter play record page. slider is hide.and press volume button slider is visible.

**Screenshots**

**Environment (please complete the following information):**
 - Target Product [Galaxy Watch,]
 - Tizen Platform Version [Tizen5.5]
 - Tizen.CircularUI Version [1.5.0]

**Additional context**

**Comment by jkpu** [comment]
You set `RotaryFocusObject="{x:Reference VolumeProgress}` . this mean display volumeProgress slider. If you want to hide volumeProgress slider. you don't set RotaryFocusObject when enter page. 
you should set RotaryFocusObject when user press volume button.

following code is example,  `OnClick` is click event of volume button
```c#
        void OnClick(object sender, EventArgs args)
        {
                RotaryFocusObject = VolumeProgress;
 
        }
```

Or, you can binding RotaryFocus object (e.g RotaryFocusTarget,  you set this value in code )

```xml
<views:CirclePageEx
    x:Name="PlaybackPage"
   x:Class="VoiceMemo.Views.PlayBackPage"
   xmlns="http://xamarin.com/schemas/2014/forms"
   xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
   xmlns:converters="clr-namespace:VoiceMemo.Converters;"
   xmlns:views="clr-namespace:VoiceMemo.Views;"
   xmlns:vm="clr-namespace:VoiceMemo.ViewModels;"
   xmlns:w="clr- namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
    RotaryFocusObject="{Binding RotaryFocusTarget}">
```
