### ISSUE TITLE
Legacy project crash when run against various Target versions

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#288]
**Describe the bug**
This may well be a framework bug rather than CircularUI but i cannot reproduce on other than wearable.

Programming will function correctly on target Tizen4 on the v4 emulator.
Running this on the Tizen 5.5 emulator will hang when launching debug.

Attempting to use same programming targeting Tizen 5.5 on v4 emulator will hang when launching debug.  On v5.5 emulators the programming will crash after attempting to update the Page content.

**To Reproduce**
Using programming in repo
https://github.com/axa88/TizenWearablePageSwitchTests

1. Set startup project TizenWearablePageSwitchTests (Tizen 4 project)
2. Run project on v4 emulator.
3. When startup page loads, select an item in CircleListView (home or job)
4. Observe this projects switches page with **NO problem**.
![image](https://user-images.githubusercontent.com/13371986/80919045-eb60e380-8d35-11ea-8f83-a159e451f2cd.png)
![image](https://user-images.githubusercontent.com/13371986/80919063-f9166900-8d35-11ea-8a82-dc7ce579c015.png)

5. Run the same project on v 5.5 emulator
6. Observe hang when launching debug
![image](https://user-images.githubusercontent.com/13371986/80918622-ef8c0180-8d33-11ea-911c-f096e5d74329.png)
(is v4 target compatible with 5.5 emulator?)

7. Set startup project to Tizen55WearablePageSwitch (Tizen 5.5 project)
8. Run project on v4 emulator
10.  Observe hang when launching debug
![image](https://user-images.githubusercontent.com/13371986/80918624-f31f8880-8d33-11ea-868f-b1ffce7daf57.png)
(is v5.5 target compatible with 4 emulator?)

11. Run Tizen55WearablePageSwitch on v5.5 emulator
12. If/when startup page loads, select an item in the CircleListView ("home" or "job")
13. **Observe project crash when attempt to switch page**

**Expected behavior**
Unless there is documented breakage, it is expected that a project targeted Tizen 5.5 project will run the same programming with the same function when targeting Tizen 4.0.

**Screenshots**

**Environment (please complete the following information):**
 ![image](https://user-images.githubusercontent.com/13371986/80918672-2d892580-8d34-11ea-9754-3ac8e5da8584.png)
![image](https://user-images.githubusercontent.com/13371986/80918718-6a551c80-8d34-11ea-9c72-9c966f096cd3.png)
![image](https://user-images.githubusercontent.com/13371986/80918756-9a042480-8d34-11ea-8813-1da186c631a1.png)
![image](https://user-images.githubusercontent.com/13371986/80918788-a5575000-8d34-11ea-8e01-6c954c5d3740.png)
- Tizen.CircularUI Version1.4.0

**Additional context**
Perhaps not CircularUI related as limited test on Mobile target hinted same behavior.

**Comment by jkpu** [comment]
Same issue is reported tizen .net forum.
https://developer.tizen.org/forums/tizen-.net/what-recommended-tooling-develop-tizen.net-applications-going-forward

This issue is not related CircularUI nuget. Maybe it  can be related emulator or Native API backward compatibility.

**Comment by axa88** [comment]
> This issue is not related CircularUI nuget. Maybe it can be related emulator or Native API backward compatibility.

@jkpu 
Yes this is same issue.
Could you help forward this issue to correct place, I agree it probably is not CircularUI library related.  Sample provided will crash without exception, so I cannot catch anything to get additional information.

**Comment by rookiejava** [comment]
I'm not sure yet, but it seems to be an internal problem with the Tizen 5.5 native UI framework.

In more detail, the problem seems to occur when using `TapGestureRecognizer` with `ListView` (even `CircleListView`), `ViewCell` and `StackLayout`.

So, I recommend using `ListView.ItemSelected` event instead of `TapGestureRecognizer` until more specific cause is identified.

(I've checked that the page switched correctly by using `ItemSelected` event,  on Tizen 5.5)

/cc @arosis78 Could you please take look on this?

**Comment by axa88** [comment]
> (I've checked that the page switched correctly by using `ItemSelected` event, on Tizen 5.5)


I confirm both programming for API4 and API6 will run on v 5.5 emulator when removing `TapGestureRecognizer` but API6 programming still not run on v 4 emulator.
Maybe that is expected?

**Comment by rookiejava** [comment]
Just like android, Tizen's API Level means that uniquely identifies the platform API revision provided by a version of the Tizen. 

The table below specifies the API Level supported by each version of Tizen platform.

| Platform Version  | API Level | TFMs |
| ------------- | ------------- |------------- |
| Tizen 4.0  | API4  | tizen40 |
| Tizen 5.0  | API5   | tizen50 |
| Tizen 5.5  | API6    | tizen60 |

Applications can use a manifest element (`api-version`)  to describe the API Level under which the application is able to run. 

```xml
<manifest xmlns="http://tizen.org/ns/packages" api-version="4" ..../>
```

When the user attempts to install an application, the Tizen platform checks the `api-version` in the application's manifest (`tizen-manifest.xml`). The Tizen platform allows the installation to begin only if `api-version` values must be equalt to or greater than the Tizen platform's API Level.

So if you try to run the application declared as API6 on tizen 4.0 platform (platform's API level  is API4), this is not allowed. (The opposite is possible because the Tizen platform basically guarantees backward compatibility.)

**Comment by axa88** [comment]
Im very glad to have variable data in VS debug now using emulator v5.5.

**Comment by axa88** [comment]
@rookiejava 

Is there a plan to support or fix `TapGestureRecognizer` for use with lists?

**Comment by rookiejava** [comment]
> Is there a plan to support or fix TapGestureRecognizer for use with lists?

Sure. As I mentioned above, this is a internal platform issue. It is expected to be resolved when a new version of the 5.5 emulator is released. (I don't know the exact time, but I expect it will be updated soon.)

And, when I checked it in the latest 5.5 binary internally, I confirmed that the example you attached works fine.

**Comment by axa88** [comment]
@rookiejava

When will new 5.5 emulator be released?
If no way for me to track this, what is the release verison that has this fix?

**Comment by rookiejava** [comment]
@axa88 
As you can see [here](https://developer.tizen.org/ko/tizen/release-notes/tizen-5.5-public-m3), Tizen 5.5 public M3 released yesterday. It doesn't look like the emulator binary has been updated yet, but I expect it to be updated soon.

**Comment by rookiejava** [comment]
Alternatively, you can directly download and create an emulator image in the following way.

1. Download the latest emulator binary [here](http://download.tizen.org/releases/milestone/tizen/5.5-unified/tizen-5.5-unified_20200812.1/images/emulator/wearable-emulator-circle/tizen-5.5-unified_20200812.1_wearable-emulator-circle.tar.gz).
2. Extract the file (`tizen-5.5-unified_20200812.1_wearable-emulator-circle.tar.gz`).
3. Run the `Emulator Manager`.
4. Click the '+ Create' button to create a new emulator image.
5. Choose the wearable-5-5-circle-x86(basic) and Click `Next`
![image](https://user-images.githubusercontent.com/1029134/91524050-2d431480-e939-11ea-8b90-7d641c33cfcb.png)
6. Select the Image format as "raw" and enter the directory path where you extracted the compressed file in step 2.
![image](https://user-images.githubusercontent.com/1029134/91524223-a0e52180-e939-11ea-947e-184cb53c853c.png)
![image](https://user-images.githubusercontent.com/1029134/91524118-65e2ee00-e939-11ea-8ab5-6bf004c7d4c3.png)
7. Click `Next`.
![image](https://user-images.githubusercontent.com/1029134/91524242-aa6e8980-e939-11ea-9f4e-d9180c369b1c.png)
7. Click `Next`.
![image](https://user-images.githubusercontent.com/1029134/91524252-ae021080-e939-11ea-830b-146db9c07b3a.png)
7. Click `Complete`.
![image](https://user-images.githubusercontent.com/1029134/91524261-b22e2e00-e939-11ea-8f69-f4df8bc7e718.png)

Enjoy!
