### ISSUE TITLE
[ActionButton] Change text color

### ISSUE THREAD

**Issue by Machinero** [Samsung/Tizen.CircularUI#292]
I didn't find TextColor property in ActionButton. It is possible way to change text color on these button?

**Comment by myroot** [comment]
Impossible to change text color of ActionButton

**Comment by patuwwy** [comment]
Could You add some property to change text color? I need it too.

**Comment by myroot** [comment]
Why do you use ActionButton instead of Button?
If you want oval shape button, you can make with ContentButton

**Comment by rookiejava** [comment]
Plus, you can also make the `Xamarin.Forms.Button` look the same as the `ActionButton` through TizenSpecific API (`Style`). See [here](https://developer.samsung.com/tizen/blog/en-us/2020/04/06/style-your-buttons-using-tizen-net) for more detail.

**Comment by patuwwy** [comment]
Ok. Thank You!
