### ISSUE TITLE
CircleListView HorizontalScrollBarVisibility doesn't work

### ISSUE THREAD

**Issue by MaxGsomGsom** [Samsung/Tizen.CircularUI#307]
**Describe the bug**
VerticalScrollBarVisibility = ScrollBarVisibility.Never doesn't work

**Environment**
 - Tizen 4 Emulator
 - Tizen.CircularUI 1.5 pre
- Tizen.NET 6.0.0.14995
- Xamarin Forms 4.6.0.726

**Comment by jkpu** [comment]
Thank you for issue reporting.
This issue was fixed at https://github.com/Samsung/Tizen.CircularUI/pull/308
We will release Tizen.CircularUI 1.5 stable release nuget in end of May.
