### ISSUE TITLE
CircularListView ContextAction or Long Holding action

### ISSUE THREAD

**Issue by EmilAlipiev** [Samsung/Tizen.CircularUI#326]
I cannot figure out if ContextActions working for CircularListView or not? I simply tried like below but nothing happening. What is the best way to delete an item from the list? is there any contextactions or long holding action?

```
 <cui:CircleListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <ViewCell.ContextActions>
                            <MenuItem Command="{Binding DeleteItem}"
                                      CommandParameter="{Binding .}"
                                      Text="Delete" IsDestructive="True" />
                        </ViewCell.ContextActions>
                        <Label Text="{Binding Name}"
                               VerticalOptions="Center"
                               HorizontalOptions="Center"
                               VerticalTextAlignment="Center"
                               HorizontalTextAlignment="Center">
                            
                        </Label>
                    </ViewCell>
                </DataTemplate>
            </cui:CircleListView.ItemTemplate>
```

**Comment by rookiejava** [comment]
Hi @EmilAlipiev, thanks for reaching out!
This is good question. As you said, this feature is currently missing from the Tizen implementation.  We’re internally working on some ideas to make it possible to select items through long press and perform user-defined action. We’ll share them soon. Thanks! 🤙

**Comment by EmilAlipiev** [comment]
@rookiejava thanks for the suggestion. I try to implement like in the [ XUIComponents sample ](https://github.com/Samsung/Tizen.CircularUI/blob/b79bfe508517efabeed55268b7a89933e05951bf/sample/XUIComponents/UIComponents/UIComponents/Samples/CircleList/StyleSelectMode.xaml)

ItemLongPressed is defined on GenList in ElmSharp namespace. i thought CircleListView inherits from xamarin.listview. How does it work together with GenList ? I am able to bind Command but somehow Commandparameter doesnt work for me.

So i have implemented like below. can I expect a the single item as I long press on a single item on the list? or effect:ItemLongPressEffect Command is executed on the entire CircleListView ? so it will return all Items as Commandparameter?

```
            <cui:CircleListView x:Name="ListExercises"
                                AbsoluteLayout.LayoutBounds="0, 0, 1, 1"
                                AbsoluteLayout.LayoutFlags="All"
                                IsGroupingEnabled="True"
                                HasUnevenRows="True"
                                GroupDisplayBinding="{Binding Key}"
                                ItemsSource="{Binding Items}"
                                SelectedItem="{Binding SelectedItem}"
                                effect:ItemLongPressEffect.Command="{Binding Path=BindingContext.LongClickCommand, Source={x:Reference Name=ListExercises}}" 
                                effect:ItemLongPressEffect.CommandParameter="{Binding .}">

 public Command LongClickCommand
        {
            get
            {
                return new Command<Item>((item) =>
                {

                    
                });
            }
        }
```
