### ISSUE TITLE
Xamarin.Forms.CarouselPage - support bezel rotation

### ISSUE THREAD

**Issue by patuwwy** [Samsung/Tizen.CircularUI#328]
**Is your feature request related to a problem? Please describe.**
1.5.0-pre7

Could Xamarin.Forms.CarouselPage support bezel rotation to change active page in the same way as CarouselView does, out of the box ?

**Additional context**
I could use CarouselView but I don't want to define ItemSource data.

**Comment by rookiejava** [comment]
You may already know, but CarouselPage has been superseded by CarouselView as you can see in the [Xamarin Docs](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/navigation/carousel-page).

> **Important**
> The CarouselPage has been superseded by the CarouselView, which provides a scrollable layout where users can swipe to move through a collection of items. For more information about the CarouselView, see Xamarin.Forms CarouselView.

> **Note**
>The CarouselPage does not support UI virtualization. Therefore, performance may be affected if the CarouselPage contains too many child elements.

It is also true that we are no longer adding/improving new features for existing CarouselPage. 

We'll reconsider the request you've said. But before that, if you must use CarouselPage and want to switch pages through bezel interaction, consider using [`RotaryEventManager`](https://samsung.github.io/Tizen.CircularUI/api/Tizen.Wearable.CircularUI.Forms.RotaryEventManager.html).

e.g.,
```cs
RotaryEventManager.Rotated += (s, e) =>
{
     if (e.IsClockwise)
     {
          //move current page clockwise
     }
     else
     {
        // move current page counterclockwise
     }
};
```

**Comment by EmilAlipiev** [comment]
Does CarousalPage replaceses IndexPage in 1.5.0 pre? I couldnt figure out how to use it together with IndicatorView. It is also experiemental by Xamarin. Is it a good idea to replace it?

**Comment by patuwwy** [comment]
> Does CarousalPage replaceses IndexPage in 1.5.0 pre? I couldnt figure out how to use it together with IndicatorView. It is also experiemental by Xamarin. Is it a good idea to replace it?

In my case, adding IndicatorView crashes application, i follow this guide https://docs.microsoft.com/pl-pl/xamarin/xamarin-forms/user-interface/indicatorview#create-an-indicatorview

**Comment by ismasanchez** [comment]
Hi, I don't quite understand why the IndexPage has been deprecated without a "real" alternative. CarouselPage can have contentpage but you have to build your own page indicator, and is going to be deprecated soon too.
CarouselView is not meant to contain ContentPages, but the same type of data through ItemTemplates, I don't see this as a real alternative to IndexPage (so useful in apps for watches by the way)
Anyway, congrats for the good work on CircularUI!

**Comment by rookiejava** [comment]
> Does CarousalPage replaceses IndexPage in 1.5.0 pre? I couldnt figure out how to use it together with IndicatorView. It is also experiemental by Xamarin. Is it a good idea to replace it?

@EmilAlipiev 
Use `IndicatorView` with `CarouselView` not `CarouselPage`. And, you are right. `IndicatorView` is still experimental feature on Xamarin.Forms. But, I think this is right direction.

<hr/>

> In my case, adding IndicatorView crashes application when i followed this guide

@patuwwy 
It works well, as we already covered in #330. ^^

<hr/>

> CarouselPage can have contentpage but you have to build your own page indicator, and is going to be deprecated soon too.
CarouselView is not meant to contain ContentPages, but the same type of data through ItemTemplates, I don't see this as a real alternative to IndexPage (so useful in apps for watches by the way)

@ismasanchez 
Yes. The `CarouselPage` may disappear soon. (not yet) For the same reason, we recommend using the `CarouselView`. But as you said, `CarouselView` is not `MultiPage`, and if you still want to use `MultiPage` for any reason, we recommend to use `CarouselPage` instead.

Unlike many people who expected the `IndexPage` to provide special features, in fact, in fact this was just a multi-page without any special features. (It is actually a subset of `CarouselPages`.) This misunderstanding has caused many issues with `IndexPages` both internally and externally.

If the current `CarouselPage` does not work properly on the Galaxy Watch, we will improve to Xamarin.Forms (not Circular UI). 

Plus, when the `CarouselPage` deprecated from Xamarin.Forms, we will reconsider providing `IndexPage` again.

Thank you for your feedback. :)

**Comment by EmilAlipiev** [comment]
Coming back to this issue. I think what we need is a tabbedpage. we mostly used indexedpage like tabbedpage. Can we get something like that where we can have different views on a multi page?
