### ISSUE TITLE
Drawing issue when migrating CirclePage + ActionButton to ContentPage + Button + Style = Bottom

### ISSUE THREAD

**Issue by axa88** [Samsung/Tizen.CircularUI#331]
**Describe the bug**
Attempting to migrate away from `CirclePage`, It appears that the rendering for a Bottom `Button `on the `ContentPage `is drawn differently than that of the legacy `CirclePage `with `ActionButton`

Using the Legacy `CirclePage`, making the `ActionButton `visible will result in a button anchored to the bottom of the page, drawn in an aesthetically pleasing way with no dead space:
![image](https://user-images.githubusercontent.com/13371986/84967048-0c607680-b0e1-11ea-8328-0355aa1e1520.png)

 

When migrating as suggested to a `ContentPage `with `Button ` using Tizen specific Style `ButtonStyle.Bottom`:

```
ActionButton = new Button {BackgroundColor = Color.Orange};
ActionButton.On<Xamarin.Forms.PlatformConfiguration.Tizen>().SetStyle(ButtonStyle.Bottom);
```

The Bottom `Button` appears to be drawn in a less aesthetically pleasing way where there is dead space between the button and the page content above it:
![image](https://user-images.githubusercontent.com/13371986/84968086-afb28b00-b0e3-11ea-8158-9c15c34d2ceb.png)

The difference between the 2 is in order to make the button appear at the bottom of the page, the content of the page and the button, are now placed inside of an additional `StackLayout`:

```
var profileEditScrollView = new CircleScrollView { Content = profileEditView };
var stackLayout = new StackLayout { Children = { profileEditScrollView, ActionButton } };
Content = stackLayout;
```
This additional `StackLayout `was not needed with Legacy `CirclePage `+ `ActionButton`

**Expected behavior**
There should be a way to anchor a bottom button to the screen and have it draw like `CirclePage `with `ActionButton`

**Environment (please complete the following information):**
 - Target Product:
![image](https://user-images.githubusercontent.com/13371986/84967441-ef787300-b0e1-11ea-932b-a33d112f5ccf.png)

 - Tizen Platform Version [Tizen 5.5]
 - Tizen.CircularUI Version [1.5.0 pre7]

**Additional context**
If this is not recommended please advise.  I do not see better code example than:
https://developer.samsung.com/tizen/blog/en-us/2020/04/06/style-your-buttons-using-tizen-net

What is c# equivalent to suggested:
`AbsoluteLayout.LayoutBounds="75, 268, 210, 92"`
from: https://github.com/Samsung/Tizen.CircularUI/releases/tag/beta-1.5.0-pre7

**Comment by rookiejava** [comment]
@axa88, can you share the code you tested so that we can accurately reproduce the problem?

> What is c# equivalent to suggested:
> AbsoluteLayout.LayoutBounds="75, 268, 210, 92"

here it is
```cs
AbsoluteLayout.SetLayoutBounds(ActionButton, new Rectangle(75, 268, 210, 92));
```

**Comment by axa88** [comment]
I created repository here to demonstrate issue.
https://github.com/axa88/BottomButtonTest

Initial drawing of Bottom `Button `on `ContentPage `shows issue described above.
Redraw of Bottom `Button `on `ContentPage `shows new issue below:
![image](https://user-images.githubusercontent.com/13371986/85088511-4ea3b980-b1ae-11ea-8f4f-3ccacbf76fc7.png)

To reproduce, load solution in repository, and switch between Pages using Bottom Buttons.

**Comment by myroot** [comment]
![image](https://user-images.githubusercontent.com/1029155/85240774-54cabc00-b474-11ea-8503-3d5470e75369.png)
Because you use `StackLayout` each child can't overlap

**Comment by myroot** [comment]
Fixes your code
``` diff
-                       var stackLayout = new StackLayout { Children = { profileEditScrollView, actionButton } };
-                       MainPage = new ContentPage { Content = stackLayout };
+                       var absoluteLayout = new AbsoluteLayout();
+                       absoluteLayout.Children.Add(profileEditScrollView, new Rectangle(0, 0, 1, 1), AbsoluteLayoutFlags.All);
+                       absoluteLayout.Children.Add(actionButton, new Rectangle(0, 1, 360, 92), AbsoluteLayoutFlags.PositionProportional);
+                       MainPage = new ContentPage { Content = absoluteLayout };
```
![abslayout](https://user-images.githubusercontent.com/1029155/85241152-d5d68300-b475-11ea-94a3-5bacf364bfd0.gif)

**Comment by axa88** [comment]
@myroot 
Thanks, this fixes my issue.
I must learn more about layout design in XF
