### ISSUE TITLE
Button background color reverted to dark blue when it's pressed and hold

### ISSUE THREAD

**Issue by bangfutao** [Samsung/Tizen.CircularUI#345]
**Describe the bug**
A few buttons in my native app with green background color, they are looking as expected. But once the button is pressed (activated), the button color reverted back to dark blue.

Here is the API code used to change the background color:
elm_object_color_class_color_set(btn, "bg", 0x04, 0x25, 0x26, 0xFF);

Tested on Watch Active 2 device, and app written in tizen-3.0.

Please see the picture for references:
![before](https://user-images.githubusercontent.com/55276260/89735797-e7dba780-da5c-11ea-9a6d-f5728c3e6c44.PNG)
![after](https://user-images.githubusercontent.com/55276260/89735800-ec07c500-da5c-11ea-8f53-96ed6dc6f242.PNG)

Thank you!

**Comment by myroot** [comment]
It looks not related CircularUI issue, so I close it

For your information, you should set `effect` and `effect_pressed` to change background color of pressed instead of `bg`
