### ISSUE TITLE
I am not able to run demo tizen wearable app

### ISSUE THREAD

**Issue by slim-shah** [Samsung/Tizen.CircularUI#353]
Hello Samsung Developer's community,

My name is Meet I am new to Tizen development. Earlier I tried loading demo app on tizen emulator and it was working fine. But suddenly after I tried loading companion app it stopped working.

Am i getting following message for every sample app i try to run (even for HelloAccessory Companion app for .net)

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in Unknown Module.
Could not load file or assembly 'Xamarin.Forms.Platform.Tizen, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Can anyone please tell me why i am facing this error ?

Thank You in Advance.

**Comment by myroot** [comment]
To use Samsung Accessory Protocol API(SAP) on emulator need to install Samsung Wearable Extension package, 
but a new released SAP API was not support tizen emulator anymore
