### ISSUE TITLE
Missing dependency to the SkiaSharp.Views.Forms in the 1.5.2 Tizen.Wearable.CircularUI.Chart.Forms Nuget package.

### ISSUE THREAD

**Issue by AlexIsCoding** [Samsung/Tizen.CircularUI#354]
**Describe the bug**
Missing dependency to the SkiaSharp.Views.Forms in the 1.5.2 Tizen.Wearable.CircularUI.Chart.Forms Nuget package.

When using the 1.5.2. nuget package and wanting to add the new RadialProgress control to a xaml view. The compiler will complain until the SkiaSharp.View.Forms dependency is added manually to the project.

**To Reproduce**
1. Add nuget 1.5.2 of Tizen.Wearable.CircularUI.Chart to project
1. Add  Tizen.Wearable.CircularUI.Forms  namespace to xaml file
e.g. 
``` 
xmlns:cu1="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Chart.Forms"
```
2. 
Add RadialProgressbar to view
```
...
 <ContentPage.Content>
        <AbsoluteLayout >
            <cu1:RadialProgress AbsoluteLayout.LayoutBounds="0.5, 0.5, 295, 295" AbsoluteLayout.LayoutFlags="PositionProportional"
                                  Thickness="30"
                                  RadialBackgroundColor="#4f4f4f"
                                  Progress="0.00"
                                  HasLabel="False"
                                  StartAngle="-130"
                                  SweepAngle="260"/>
...
```
3. Compile
4. See error like:
_value of type 'RadialProgress' cannot be added to a collection or dictionary of type 'IAbsoluteList`1_

**Expected behavior**
This shouldn't happen. The SkiaSharp.Views.Forms dependency should already be part of the nuget package. 

**Environment (please complete the following information):**
 - Target Product Galaxy Watch
 - Tizen Platform Version Tizen 4.0.0, 4.0.3, 5.0, ....]
 - Tizen.CircularUI Version 1.5.2

**Additional context**
I only found this to be the reason, while looking in the csproj file of the example project where a preview version is referenced.

https://github.com/Samsung/Tizen.CircularUI/blob/master/src/Tizen.Wearable.CircularUI.Chart.Forms/Tizen.Wearable.CircularUI.Chart.Forms.csproj)

**Comment by rookiejava** [comment]
Please refer to #355.
