### ISSUE TITLE
MediaPlayer Seek does not work properly during playback

### ISSUE THREAD

**Issue by Luk164** [Samsung/Tizen.CircularUI#358]
**Describe the bug**
When a video is being played seeking is not working properly. It works as expected while paused.

I have the following code for seeking forward and rewinding a video:

```
RotaryEventManager.Rotated += (sender, args) =>
{
    if (args.IsClockwise)
    {
        //Forward video
        Device.BeginInvokeOnMainThread(() => {
            Player.Seek(Player.Position + 2000);
        });
    }
    else
    {
        //Reverse video
        Device.BeginInvokeOnMainThread(() => {
            Player.Seek(Player.Position - 2000);
        });
    }
};
```

Here is the xaml:

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="MyAppTTS.Views.MediaViewPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:c="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
    xmlns:viewModels="clr-namespace:MyAppTTS.ViewModels">
    <ContentPage.BindingContext>
        <viewModels:MediaViewViewModel/>
    </ContentPage.BindingContext>

    <ContentPage.Content>
        <c:MediaView>
            <c:MediaPlayer
                x:Name="Player"
                AutoPlay="False"
                Source="sample-mp4-file.mp4"
                UsesEmbeddingControls="true"
                BufferingStarted="OnBufferingStarted"
                BufferingCompleted="OnBufferingCompleted"
                PlaybackStarted="OnPlaybackStarted"
                PlaybackPaused="OnPlaybackPaused"
                PlaybackStopped="OnPlaybackStopped"
                PlaybackCompleted="OnPlaybackCompleted" />
        </c:MediaView>
    </ContentPage.Content>
</ContentPage>
```

**To Reproduce**
1. Use the provided code to make a view
2. Start playing video
3. Rotate bezel
4. Pause video
5. Rotate bezel

**Expected behavior**
Seeking works the same if the video is playing or paused.

**Environment (please complete the following information):**
 - Target Product: Galaxy Watch
 - Tizen Platform Version: Tizen 4.0.0
 - Tizen.CircularUI Version: 1.5.2

**Comment by myroot** [comment]
Hi, I identify this issue
It seems limitation of platform media player. it is working well if seeking enough long different time (for example `Seek(Player.Position + 5000)`)

**Comment by Luk164** [comment]
@myroot I also noticed these two functions that do not seem to be documented:

- FastForwardCommand
- RewindCommand

If executed like this: `Player.FastForwardCommand.Execute(null);` They seem to seek +/- 5s.
