### ISSUE TITLE
CircleListView within CarouselView crashes when the ListView has been swiped away before the animation ends

### ISSUE THREAD

**Issue by KieronQuinn** [Samsung/Tizen.CircularUI#364]
**Describe the bug**
When using one (or more) CircleListView within a CarouselView, if the user swipes away from the focused CircleListview while the animation is still running (ie. they scroll by swipe or rotary action then swipe away), the app will hard crash with a NullReferenceException.

**To Reproduce**
1. Create a CarouselView containing two 'pages', containing one or more CircleListView (my setup has the second page with a CircleListView, the first page is dynamic between a CircleScrollView and a CircleListVIew)
2. Open the app and swipe to the second page
3. Scroll up and down a few times, then swipe off the page back to the first.
4. The app will crash with the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tizen.Wearable.CircularUI.Forms.Renderer.CircleListViewRenderer.OnScrollAnimationStopped(Object sender, EventArgs args)
```

**Expected behavior**
The page should be swiped away without issue

**Screenshots**
[First page (scrollview)](https://i.imgur.com/kdeSmW1.png)
[Second page (circlelistview)](https://i.imgur.com/V6oNeig.png)

**Environment (please complete the following information):**
 - Target Product: Galaxy Watch Active 2
 - Tizen Platform Version: 5.5.0.2
 - Tizen.CircularUI Version: 1.5.3

**Comment by rookiejava** [comment]
> Nope. I actually abandoned my whole Tizen project entirely and intend to switch to the new WearOS powered watch in the next couple of weeks. Tizen turned out to just be too buggy and annoying to develop on.

My Bad. I'm sorry to check this issue too late. We will check and get back as soon as possible. 
(/cc @shyunMin @sung-su @JoonghyunCho )


> you know if we can find a solution for this? :) just tagging in case if you have missed it thanks

Thank you for reminding me. :-)

**Comment by shyunMin** [comment]
Hello @KieronQuinn, sorry again for the late answer.
We tested a scenario like you said with CarouselView, ScrollView and CircleListView, and the issue is not reproduced on an emulator, unfortunately. We will test it on the target product as soon as we get to find one.

<img width="300" src="https://user-images.githubusercontent.com/20968023/132451221-61e7fb12-fe92-48cd-9ff3-c99f8938ef85.PNG" />
<img width="300" src="https://user-images.githubusercontent.com/20968023/132451228-bf355598-876e-4186-9fda-425ca559718f.PNG" />

**Comment by KieronQuinn** [comment]
I vaguely recall that it might have worked in the emulator but not on device, but I was unable to get an internet connection to work on the emulator so it was hard to test.

**Comment by shyunMin** [comment]
Hello @KieronQuinn,
I've checked the issue and pushed the patch to fix it. I'll let you know as soon as a new package applied the change is published.
Thanks for reporting the issue.

**Comment by shyunMin** [comment]
Just in case you missed. Fixed package has been released! Thanks.
https://github.com/Samsung/Tizen.CircularUI/releases/tag/release-1.5.4
