### ISSUE TITLE
UI offsets downwards when wrapped into NavigationPage

### ISSUE THREAD

**Issue by CalamityDeadshot** [Samsung/Tizen.CircularUI#366]
**Bug description**
When the main page of the application is wrapped into NavigationPage like `MainPage = new NavigationPage(new MainPage());`, the whole application off-centers downwards. This doesn't happen without `NavigationPage` wrapper, but clearly you can't make a decent app without navigation, amaright?

**To Reproduce**
1. In App.xaml.cs assign an instance of `NavigationPage` to `MainPage`
2. Launch app
3. Observe.

**Expected behavior**
A properly centered UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/44675043/124586084-b2069500-de5e-11eb-9e2c-ab31fd3a7baf.png)
The button here is properly centered in XAML, but vertically shifted.
![image](https://user-images.githubusercontent.com/44675043/124586309-f5610380-de5e-11eb-9716-ee38123297e7.png)
And here the `CircleListView` is also off-centered.

**Environment**
 - Target Product: this happens on both emulator and a real device (Gear S3)
 - Tizen Platform Version: 4.0.0.7, also tested on ver. 6 (emulated)
 - Tizen.CircularUI Version: 1.5.0, also tested on 1.5.3

**Comment by myroot** [comment]
Set false on HasNavigationBar property

https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.navigationpage.sethasnavigationbar?view=xamarin-forms#Xamarin_Forms_NavigationPage_SetHasNavigationBar_Xamarin_Forms_BindableObject_System_Boolean_

**Comment by CalamityDeadshot** [comment]
It's quite inconvenient to have to set this property to every single page, but anyways, thanks!
