### ISSUE TITLE
[CircularUI] [CirclePage.ActionButton] Issue when using entry

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#76]
I have 2 controls on CircularPage. One is entry located on top and ActionButton on bottom of the screen.

![action1](https://user-images.githubusercontent.com/39958609/42631322-6700e4ca-85c9-11e8-829d-ac3eb787a995.png)

Problem occurs when entry is focused. ActionButton is not hiding under keyboard, it moves along with a keyboard.

![action2](https://user-images.githubusercontent.com/39958609/42631349-7d02b06e-85c9-11e8-9b37-75479fd445b9.png)

Can you fix this? Or i need to find a way to not use this two controls together? In my opinion it shouldn't be working like that :)

**Comment by jsobczuk** [comment]
I found a way to ommit this problem. But still I don't know if it's a proper solution. It works good actually but still i think it should be fixed. I added 2 events to Entry : Focused and Unfocused.
```cs
        private void Entry_Focused(object sender, Xamarin.Forms.FocusEventArgs e)
        {
            ActionButton.IsVisible = false;
        }

        private void Entry_Unfocused(object sender, Xamarin.Forms.FocusEventArgs e)
        {
            Device.StartTimer(TimeSpan.FromMilliseconds(65), () =>
            {
                ActionButton.IsVisible = true;
                // return false to run the timer callback only once
                return false;
            });
        }
```

Timer is set to make a delay when hiding Action Button. It prevents "flickering" effect.

**Comment by jkpu** [comment]
If you want to use entry in CirclePage or circle device. 
Please use PopupEntry(https://samsung.github.io/Tizen.CircularUI/guide/PopupEntry.html) instead of Entry.
We have added PopupEntry becaue there were many issue in Entry with circular device.

**Comment by jsobczuk** [comment]
I made a simple application with PopupEntry based on link you have sent to me. Here is the xaml code:
```cs
<?xml version="1.0" encoding="utf-8" ?>
<cui:CirclePage xmlns="http://xamarin.com/schemas/2014/forms"
                xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                xmlns:viewModels="clr-namespace:QRCodeGenerator.ViewModels;assembly=QRCodeGenerator"
                x:Class="QRCodeGenerator.Tizen.Wearable.Views.PasswordPage"
                xmlns:cui ="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
                NavigationPage.HasNavigationBar="False">

    <cui:CirclePage.BindingContext>
        <viewModels:PasswordViewModel />
    </cui:CirclePage.BindingContext>

    <cui:CirclePage.Content>
        <cui:CircleStackLayout>
            <cui:PopupEntry Placeholder="Password"
                            BackgroundColor="Gray"
                            TextColor="Blue"
                            VerticalOptions="CenterAndExpand"
                            HorizontalOptions="CenterAndExpand"
                            Text="{Binding Password}" />
        </cui:CircleStackLayout>
    </cui:CirclePage.Content>

</cui:CirclePage>
```
The only thing that is changed is that ContentPage is changed to CirclePage, but problem also occured when I was testing it on ContentPage. In this case I need CirclePage to use ActionButton.

Problem i have encountered is after focusing on entry . Background over the keyboard is set to grey but entry remains in same place as before. Second screen is taken after I typed "A".

![popupentry1](https://user-images.githubusercontent.com/39958609/42779740-96f3ea80-8941-11e8-938e-000ec173a06e.png)
 
![popupentry2](https://user-images.githubusercontent.com/39958609/42779749-9c860712-8941-11e8-9dcf-48ca843123cf.png)

![popupentry3](https://user-images.githubusercontent.com/39958609/42779766-a07c610e-8941-11e8-8a2f-b1bcfc6b19c5.png)

Here are my packages for whole solution:
![popupentry5](https://user-images.githubusercontent.com/39958609/42780443-74392788-8943-11e8-86c1-3588ed223b84.png)

I also tested the ActionButton issue but it seems to be working good now :)

**Comment by jkpu** [comment]
I have reproduce this issue with wearable 4.0 preview emulator. but this version of emulator binary is outdated. preview emulator binary version is tizen-4.0-unified_20180223.1 .  PopupEntry efl theme was applied about 2 month ago by nativen UI engineer. So this issue due to not applying theme of PopupEntry.
If you are samsung developer. you must use latest emulator binary or use latest Solis target binary.
You are not samsung developer. you can only wait 4.0 officail release that will apply PopupEntry native theme.

**Comment by jsobczuk** [comment]
I am Samsung developer ^^
Thanks for reply.

**Comment by jsobczuk** [comment]
I use 20180716.2 Emulator now.

```cs
<?xml version="1.0" encoding="utf-8" ?>
<cui:CirclePage xmlns="http://xamarin.com/schemas/2014/forms"
                xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                xmlns:viewModels="clr-namespace:QRCodeGenerator.ViewModels;assembly=QRCodeGenerator"
                x:Class="QRCodeGenerator.Tizen.Wearable.Views.PasswordPage"
                xmlns:cui ="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
                NavigationPage.HasNavigationBar="False">

    <cui:CirclePage.BindingContext>
        <viewModels:PasswordViewModel />
    </cui:CirclePage.BindingContext>

    <cui:CirclePage.Content>
        <cui:CircleStackLayout>
            <cui:PopupEntry PlaceholderColor="Blue"
                            Placeholder="Password"
                            BackgroundColor="AliceBlue"
                            TextColor="Blue"
                            VerticalOptions="CenterAndExpand"
                            HorizontalOptions="CenterAndExpand"
                            Text="{Binding Password}" />
        </cui:CircleStackLayout>
    </cui:CirclePage.Content>

    <cui:CirclePage.ActionButton>
        <cui:ActionButtonItem x:Name="ActionButton"
                              Text="Done"
                              Command="{Binding GoToPreviousPageCommand}" />
    </cui:CirclePage.ActionButton>

</cui:CirclePage>
```
It works good in this setup.

Still I encountered a problem:

PopupEntry is not working properly when BackgroundColor property is not set. Also the ActionButton is not working properly.  There is some sort of "flickering". Sometimes it works good but in most cases I see something like on theese 2 screens:

![popup1](https://user-images.githubusercontent.com/39958609/42814705-5953e5f2-89c5-11e8-9dca-7410ade5c347.png)
![popup2](https://user-images.githubusercontent.com/39958609/42814712-5eaa75d4-89c5-11e8-9137-f3c8b203829f.png)

You can see that ActionButton is still visible. 

It got me into question: **Why there is no option to choose if I want the keyboard screen to change the color? What if someone need Red background on PopupEntry but also need the keyboard screen to have Black background? In my opinion there should be additional attribute like KeyboardScreenBackgroundColor and when it's not set it should have default screen color (Black i think).**

**Comment by jkpu** [comment]
I  fixed  PopupEntry background transparency issue at (https://github.com/Samsung/Tizen.CircularUI/pull/78)
please update latest nuget via myget.
And your request about KeyboardScreenBackgroundColor. we will discuss about this property .
