### ISSUE TITLE
[CircularUI][Circular ListView] Header Text Color Issue

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#90]
Header Text Color in Circular ListView is diffrent than set. It seems to be dimmed , like there would be some dark layer on it.

In both examples I used same color : #4CCDFC

First screen is simple Label and second one is Header from Circular ListView:

![listviewcolor1](https://user-images.githubusercontent.com/39958609/43587411-787fa00e-966a-11e8-9332-3d928af74b83.PNG)
![listviewcolor2](https://user-images.githubusercontent.com/39958609/43587416-7b8ce572-966a-11e8-99ff-c268b3b8c525.PNG)

See also : TNEXT-16216

**Comment by idkiller** [comment]
It's not an issue.
Basically, Circular ListView works as Birds Eye mode. (Native EFL Circle List limitation)
The Birds Eye mode is basically blurry and tapered as you go up or down except for the central item.
Actually, Header color is not different but it just got blurry and Native EFL API has the same Issue.

I want to also fix this weird UX, but there seems to be no other way while wrapping the native API.
Please let me know if you can find a way to implementation.

**Comment by jsobczuk** [comment]
This behaviour is inconsistent with UX Wearable GUIDE.
There is no way to work-around this problem and it's stopping our development at this point , because we need to stick with UX GUIDE.
Either UX GUIDE needs to be changed or this behaviour needs to be fixed.
I tried to put simple Label , but it not works with ListView cause elements are getting underneath Label.

 I can't find a good implementation for this because I don't work with EFL and Native C.
Please let me know about any updates to this problem because it's blocking development.

**Comment by idkiller** [comment]
Attached CancelEffect Property help Header and Footer of CircleListView do not apply the Fisheye Effect.

```XML
<?xml version="1.0" encoding="utf-8" ?>
<w:CirclePage
    x:Class="WearableUIGallery.TC.TCCircleListViewNoEffect"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:WearableUIGallery"
    xmlns:sys="clr-namespace:System;assembly=netstandard"
    xmlns:w="clr-namespace:Tizen.Wearable.CircularUI.Forms;assembly=Tizen.Wearable.CircularUI.Forms"
    RotaryFocusObject="{x:Reference mylist}">
    <w:CirclePage.Content>
        <w:CircleListView x:Name="mylist">
            <w:CircleListView.ItemsSource>
                <x:Array x:Key="array" Type="{x:Type sys:String}">
                    <x:String>Item 1</x:String>
                    <x:String>Item 2</x:String>
                    <x:String>Item 3</x:String>
                    <x:String>Item 4</x:String>
                    <x:String>Item 5</x:String>
                    <x:String>Item 6</x:String>
                    <x:String>Item 7</x:String>
                    <x:String>Item 8</x:String>
                    <x:String>Item 9</x:String>
                    <x:String>Item 10</x:String>
                    <x:String>Item 11</x:String>
                    <x:String>Item 12</x:String>
                </x:Array>
            </w:CircleListView.ItemsSource>
            <w:CircleListView.Header>
                <x:String>Header</x:String>
            </w:CircleListView.Header>
            <w:CircleListView.Footer>
                <x:String>Footer</x:String>
            </w:CircleListView.Footer>
            <w:CircleListView.ItemTemplate>
                <DataTemplate>
                    <ViewCell>
                        <Label Text="{Binding .}" HorizontalTextAlignment="Center"/>
                    </ViewCell>
                </DataTemplate>
            </w:CircleListView.ItemTemplate>
            <w:CircleListView.HeaderTemplate>
                <DataTemplate>
                    <Label
                        w:CircleListView.CancelEffect="True"
                        FontAttributes="Bold"
                        FontSize="Large"
                        HorizontalTextAlignment="Center"
                        Text="{Binding .}"
                        TextColor="Red" />
                </DataTemplate>
            </w:CircleListView.HeaderTemplate>
            <w:CircleListView.FooterTemplate>
                <DataTemplate>
                    <Label
                        w:CircleListView.CancelEffect="True"
                        FontAttributes="Bold"
                        FontSize="Large"
                        HorizontalTextAlignment="Center"
                        Text="{Binding .}"
                        TextColor="Blue" />
                </DataTemplate>
            </w:CircleListView.FooterTemplate>
        </w:CircleListView>
    </w:CirclePage.Content>
</w:CirclePage>
```

**Comment by jsobczuk** [comment]
I see that only thing that changed is 
```cs
w:CircleListView.CancelEffect="True"
```w:CircleListView.CancelEffect="True"
It is compiling in my code, but I have emulator crash when I create a page. Also I have error before compiling (even though it compiles) that this property cannot be found.

**Comment by jsobczuk** [comment]
OK so I updated CircularPackage and it works but I don't see any change in Header Color :)

**Comment by jkpu** [comment]
Did you test with latest nuget version?  CancelEffect="True" commit has been merged latest. so please check latest nuget package.

**Comment by jsobczuk** [comment]
Yes I testes it on new nuget package : pre2-00084

CancelEffect="True" , does not solve this problem.

**Comment by idkiller** [comment]
I do not understand your situation. Please give me the source I can test, I solved the same problem in the emulator (tizen-4.0-unified_20180728.1_wearable-emulator-cirlce)
![w-4 0-circle-x86-preview-2018-08-22-210038](https://user-images.githubusercontent.com/891887/44462146-9870f680-a64e-11e8-98cf-27f34bcf965d.png)

**Comment by jkpu** [comment]
I have checked w:CircleListView.CancelEffect="True" with XUIComponents sample app. 
(https://github.com/Samsung/Tizen-CSharp-Samples/tree/master/Wearable/XUIComponents )

first is before. second image is after only insert  

> w:CircleListView.CancelEffect="True"

You can see Header Text color has been changed. and Label size is bigger than before because Fish Eye mode is  not set.

![w-4 0-circle-x86-preview-2018-08-28-173534](https://user-images.githubusercontent.com/31116585/44712622-33088400-aaec-11e8-807b-f4ed45ff6690.png)

![w-4 0-circle-x86-preview-2018-08-28-175549](https://user-images.githubusercontent.com/31116585/44712631-36037480-aaec-11e8-86a7-0551a89c0772.png)

**Comment by jsobczuk** [comment]
I see in your screens that it's really working, still don't know why it's not working at my app.

I will get new emulator and instal newest circular package (95 pre-release) and maybe it will help if not I will come back here.

Thanks for help with that issue.
