### ISSUE TITLE
[CircularUI][ActionButton] Build Warning

### ISSUE THREAD

**Issue by jsobczuk** [Samsung/Tizen.CircularUI#97]
Hi

I am preparing sample app for tests. I use ActionButton on 4 pages and i get 4 warnings like this one:

![warning1](https://user-images.githubusercontent.com/39958609/44312386-61ed6e80-a3f7-11e8-942b-b52e2d20d467.PNG)

Problem is located in InitializeComponent() function. Declaration of InitializeComponent() is in metadata files with xaml.g.cs extension and theese files are generated automatically.

Adding new keyword like this removes warning, but theese files are made everytime I build project so this does not solve problem.
```cs
        private new global::Tizen.Wearable.CircularUI.Forms.ActionButtonItem ActionButton;
```

Overiding metadata from CodeBehind file is not easy task and since application is sample app it shouldnt contain workarounds.

Could you fix this? It's blocking my application test preparation.

Best regards.

**Comment by jkpu** [comment]
please attach your application code I don't understand what is the issue.

**Comment by jkpu** [comment]
There was no warnning in sample apps which used CirclePage.
According to warnning message, I think you may redefine ActionButton property in your new class that inherit CirclePage. This not issue, you should remove ActionButton property in your new class or should use another name of property.

**Comment by jsobczuk** [comment]
Thank's a lot for help with that, I didn't know that it's a property name causing it :)
